openapi: 3.0.0
info:
  title: timesheet
  description: timesheet API
  version: '1.0'
  contact:
    name: Anjali Israni
    email: anjali.israni@sage.com
tags:
  - name: Timesheets
    description: |-
      Timesheets ensure workers are paid appropriately and help project managers invoice clients and track overall project costs and expenses over time.

      Timesheets are used in both Projects and Time & Expenses. A subscription to Projects is required to approve timesheets and save timesheets as drafts.

      Each time a timesheet entry is submitted, a timesheet approval history object is created for tracking purposes.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/timesheet:
    get:
      summary: List timesheets
      description: 'Returns up to 100 object references from the collection with a key, ID, and link for each timesheet. This operation is mostly for use in testing; use query to find timesheets that meet certain criteria and to specify properties that are returned.'
      tags:
        - Timesheets
      operationId: get-objects-timesheet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of timesheets
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List of timesheets:
                  value:
                    'ia::result':
                      - key: '101'
                        id: '101'
                        href: /objects/timesheet/101
                      - key: '102'
                        id: '102'
                        href: /objects/timesheet/102
                      - key: '103'
                        id: '103'
                        href: /objects/timesheet/103
                    'ia::meta':
                      totalCount: 3
                      start: 1
                      pageSize: 100
                      next: 0
                      previous: 0
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a timesheet
      description: Creates a new timesheet.
      tags:
        - Timesheets
      operationId: post-objects-timesheet
      requestBody:
        description: timesheet
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/timesheet'
                - $ref: '#/components/schemas/timesheetRequiredProperties'
            examples:
              Create a timesheet:
                value:
                  beginDate: '2023-01-01'
                  state: submitted
                  description: Week of 01/01/23
                  employee:
                    key: '973'
                  attachment:
                    key: '8420'
                  lines:
                    - dimensions:
                        department:
                          key: '11'
                        location:
                          key: '22'
                        project:
                          key: '1'
                        costType:
                          key: '2'
                        task:
                          key: '1'
                        customer:
                          key: '13'
                        item:
                          key: '13'
                      entryDate: '2023-04-01'
                      quantity: 6
                      description: Week of 04/01/23
                      notes: Talked to client regarding project
                      timeType:
                        key: '1'
                      isBillable: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New timesheet
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                New timesheet created:
                  value:
                    'ia::result':
                      key: '40'
                      id: '40'
                      href: /objects/timesheet/40
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
  '/objects/timesheet/{key}':
    parameters:
      - name: key
        description: System-assigned unique key for the timesheet.
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a timesheet
      description: Returns detailed information for a specified timesheet.
      tags:
        - Timesheets
      operationId: get-objects-timesheet-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the timesheet
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/timesheet'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Details of the timesheet:
                  value:
                    'ia::result':
                      key: '23'
                      id: '23'
                      href: /objects/timesheet/23
                      beginDate: '2023-01-01'
                      endDate: '2023-12-31'
                      postingDate: '2023-01-01'
                      state: submitted
                      unitOfMeasure: Hours
                      hoursInDay: 8
                      description: Week of 01/01/23
                      calculationMethod: hourly
                      postActualLaborCost: false
                      employee:
                        key: '973'
                        id: E-001
                        name: John Smith
                        firstName: John
                        lastName: Smith
                        href: /objects/employee/973
                      attachment:
                        key: '8420'
                        id: Attach-01
                        href: /objects/attachment/973
                      employeeClassId: EMP_CLS_001
                      employeeDepartmentId: DEP-11
                      employeeLocation:
                        key: '22'
                        id: LOC-22
                        href: /objects/location/22
                      employeePositionId: MGR
                      lines:
                        - key: '1411'
                          id: '1411'
                          href: /objects/timesheet-line/1411
                          timesheet:
                            key: '11'
                            id: '11'
                            href: /objects/timesheet/11
                          dimensions:
                            department:
                              key: '11'
                              id: DEP-11
                              name: Sales and Marketing
                              href: /objects/department/11
                            location:
                              key: '22'
                              id: LOC-22
                              name: California
                              href: /objects/location/22
                            employee:
                              key: '10'
                              id: EMP-10
                              name: 'Thomas, Glenn'
                              href: /objects/employee/10
                            project:
                              key: '1'
                              id: Proj-001
                              name: Implementation
                              href: /objects/project/1
                            costType:
                              id: '2'
                              key: '2'
                              name: Project Expense
                              href: /objects/cost-type/2
                            task:
                              id: '1'
                              key: '1'
                              name: Project Task
                              href: /objects/task/1
                            customer:
                              key: '13'
                              id: CUST-13
                              name: Jack In the Box
                              href: /objects/customer/13
                            item:
                              key: '13'
                              id: Case 13
                              name: Platform pack
                              href: /objects/item/13
                          entryDate: '2023-04-01'
                          quantity: 6
                          lineNumber: 1
                          description: Week of 04/01/23
                          notes: Talked to client regarding project
                          state: approved
                          timeType:
                            key: '1'
                            id: Salaries At Root
                            name: Salaries At Root
                            href: /objects/time-type/1
                          isBillable: true
                          isBilled: 'false'

                          statisticalJournal:
                            key: '7483'
                            id: '7483'
                            href: /objects/employee/10
                          billableUtilizedAccount:
                            key: '8293'
                            id: '8293'
                            href: /objects/statistical-gl-account/8293
                          nonBbillableUtilizedAccount:
                            key: '8294'
                            id: '8294'
                            href: /objects/statistical-gl-account/8294
                          billableNonUtilizedAccount:
                            key: '8295'
                            id: '8295'
                            href: /objects/statistical-gl-account/8295
                          nonBillableNonUtilizedAccount:
                            key: '8296'
                            id: '8296'
                            href: /objects/statistical-gl-account/8296
                          hours:
                            billable: 8
                            nonBillable: 2
                            approved: 10
                            approvedBillable: 8
                            approvedNonBillable: 2
                            utilized: 10
                            nonUtilized: 4
                            approvedUtilized: 3
                            approvedNonUtilized: 2
                          externalPayroll:
                            costRate: 1
                            billingRate: 1
                            amount: '90'
                            employerTaxes: 15
                            fringes: 10
                            cashFringes: 2
                          laborClass:
                            key: '15'
                            id: '15'
                            name: Labor Class
                            href: /objects/labor-class/15
                          audit:
                            createdDateTime: '2022-04-20T16:20:00Z'
                            modifiedDateTime: '2022-04-20T16:20:00Z'
                            createdBy: '1'
                            modifiedBy: '95'
                      audit:
                        createdDateTime: '2022-04-20T16:20:00Z'
                        modifiedDateTime: '2022-04-20T16:20:00Z'
                        createdBy: '1'
                        modifiedBy: '95'
                    'ia::meta':
                      totalCount: 3
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a timesheet
      description: Updates an existing timesheet by setting field values. Any fields not provided remain unchanged.
      tags:
        - Timesheets
      operationId: patch-objects-timesheet-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/timesheet'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Updates a timesheet:
                value:
                  state: submitted
                  description: Week of 01/01/23
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated timesheet
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Timesheet updated:
                  value:
                    'ia::result':
                      key: '40'
                      id: '40'
                      href: /objects/timesheet/40
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a timesheet
      description: Deletes a timesheet.
      tags:
        - Timesheets
      operationId: delete-objects-timesheet-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    timesheet:
      $ref: ../models/timesheet.s1.schema.yaml
    timesheetRequiredProperties:
      type: object
      required:
        - beginDate
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
