openapi: 3.0.0
info:
  title: contract.line
  description: contract-line API
  version: '1.0'
  contact:
    name: Niraj Kumar
    email: niraj.kumar@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: contract-line
    description: This function is applicable when using event-driven revenue recognition. It changes the Delivery status of the given contract line to Delivered.
paths:
  /services/contract/line/deliver:
    post:
      summary: contract-line deliver
      description: This function is applicable when using event-driven revenue recognition. It changes the Delivery status of the given contract line to Delivered.
      tags:
        - contract-lines
      operationId: post-contract-line-deliver
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contract-line-deliver-request'
      responses:
        '200':
          description: Executed
          content:
            application/json:
              schema:
                type: object
                properties:
                  ia::result:
                    $ref: '#/components/schemas/contract-line-deliver-response'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    contract-line-deliver-request:
      description: deliver request
      type: object
      x-mappedTo: __custom__
      required:
        - key
        - deliveryDate
      properties:
        key:
          type: string
          description: Contract line key
          x-mappedTo: CONTRACTDETAILKEY
          nullable: false
          example: '2'
        deliveryDate:
          type: string
          format: date
          description: deliver date
          x-mappedTo: DELIVERYDATE
          nullable: false
          example: '2022-01-01'
    contract-line-deliver-response:
      description: deliver response
      type: object
      x-mappedTo: __custom__
      properties:
        status:
          type: string
          description: status of the result
          x-mappedTo: STATUS
          example: completed
          enum:
            - completed
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
