openapi: 3.0.0
info:
  title: contract-expense-schedule-line
  description: contract-expense-schedule-line API
  version: '1.0'
  contact:
    name: Jim Reed
    email: jim.reed@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: Contract expense schedule lines
    description: A contract expense schedule line represents a single expense for a contract line.
paths:
  /objects/contract-expense-schedule-line:
    get:
      summary: List contract expense schedule lines
      description: Returns a collection with a key, ID, and link for each contract-expense-schedule-line.
      tags:
        - Contract expense schedule lines
      operationId: get-objects-contract-expense-schedule-line
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of contract expense schedule line objects
                properties:
                  ia::result:
                    type: array
                    items:
                      $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-pages.schema'
              examples:
                List of contract expense schedules:
                  value:
                    ia::result:
                      - key: '84'
                        id: RT-00001
                        href: /objects/contract-expense-schedule-line/84
                      - key: '85'
                        id: RT-00002
                        href: /objects/contract-expense-schedule-line/85
                      - key: '60'
                        id: RT-00003
                        href: /objects/contract-expense-schedule-line/60
                      - key: '78'
                        id: RT-00004
                        href: /objects/contract-expense-schedule-line/78
                      - key: '79'
                        id: RT-00005
                        href: /objects/contract-expense-schedule-line/79
                    ia::meta:
                      totalCount: 5
                      start: 1
                      pageSize: 100
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  ia::result:
                    $ref: '#/components/schemas/error-response.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-extended.schema'
              examples:
                List of contract expense schedule line errors:
                  value:
                    ia::result:
                      ia::error:
                        code: invalidRequest
                        message: Object named [contract-expense-schedule-line] is not supported in version [0]
                        supportId: '-hOIM%7EYagYsDEpVbp0kVn1KUJ45gAAAAQ'
                    ia::meta:
                      totalCount: 1
                      totalSuccess: 0
                      totalError: 1
  /objects/contract-expense-schedule-line/{key}:
    parameters:
      - name: key
        description: System-assigned key for the contract expense schedule line.
        in: path
        required: true
        schema:
          type: string
          example: '8241'
    get:
      summary: Get a contract expense schedule line
      description: Returns detailed information for a particular contract expense schedule line.
      tags:
        - Contract expense schedule lines
      operationId: get-objects-contract-expense-schedule-line-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the contract expense schedule line
                properties:
                  ia::result:
                    $ref: '#/components/schemas/contract-expense-schedule-line'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  href:
                    type: string
                  ia::result:
                    $ref: '#/components/schemas/error-response.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-extended.schema'
              examples:
                Update a contract expense schedule line error:
                  value:
                    key: '12'
                    href: /objects/contract-expense-schedule-line/12
                    ia::result:
                      ia::error:
                        code: invalidRequest
                        message: Field [id] is a read-only field
                        supportId: YCbdS%7EYagQGDEvVbn0UIY1o-JKOAAAAAo
                    ia::meta:
                      totalCount: 1
                      totalSuccess: 0
                      totalError: 1
components:
  schemas:
    contract-expense-schedule-line:
      type: object
      allOf:
        - $ref: '#/components/schemas/contract-expense-schedule-line.s1.schema'
        - $ref: '#/components/schemas/contract-schedule-line-typeref.s1.schema'
        - $ref: '#/components/schemas/contract-schedule-line-postable-typeref.s1.schema'
    object-reference.schema:
      title: object-reference
      type: object
      description: Reference Object definition
      properties:
        key:
          type: string
        id:
          type: string
        href:
          type: string
          readOnly: true
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    metadata-pages.schema:
      title: metadata-pages
      description: Meta data for collection response
      type: object
      allOf:
        - $ref: '#/components/schemas/metadata.schema'
        - type: object
          properties:
            start:
              type: integer
              description: Start Element Number
              x-mappedTo: null
              readOnly: true
              example: 1
            pageSize:
              type: integer
              description: Page Size
              x-mappedTo: null
              readOnly: true
              example: 100
            next:
              type: integer
              description: Next Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: 101
            previous:
              type: integer
              description: Previous Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: null
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
    metadata-extended.schema:
      title: metadata-extended
      description: Meta data with partial success
      type: object
      allOf:
        - $ref: '#/components/schemas/metadata.schema'
        - type: object
          properties:
            totalSuccess:
              type: integer
              description: Total Success
              x-mappedTo: null
              readOnly: true
              example: 2
            totalError:
              type: integer
              description: Total Errors
              x-mappedTo: null
              readOnly: true
              example: 1
    contract-expense-schedule-typeref.s1.schema:
      type: object
      title: contract-expense-schedule
      x-object: contract-expense-schedule
      properties:
        key:
          type: string
          description: Contract expense schedule system-assigned key.
          x-mappedTo: SCHEDULEKEY
          readOnly: true
          example: '145'
        id:
          type: string
          description: Contract expense schedule unique identifier.
          x-mappedTo: SCHEDULEKEY
          readOnly: true
          example: '145'
        href:
          type: string
          description: Contract expense schedule URL.
          readOnly: true
          example: /objects/contract-expense-schedule/145
      examples: []
    contract-expense-schedule-line.s1.schema:
      type: object
      title: contract-expense-schedule-line
      x-mappedTo: contractexpensescheduleentry
      x-ownedBy: contract-expense-schedule
      description: Contract expense schedule line.
      required:
        - scheduledExpenseDate
      properties:
        href:
          type: string
          description: Schedule line URL.
          readOnly: true
          example: /objects/contract-expense-schedule-line/145
        contractExpenseSchedule:
          $ref: '#/components/schemas/contract-expense-schedule-typeref.s1.schema'
      examples: []
    audit.s1.schema:
      type: object
      title: audit
      properties:
        createdDateTime:
          description: Time of the submission
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENCREATED
          readOnly: true
        modifiedDateTime:
          description: Time of the modification
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENMODIFIED
          readOnly: true
        createdBy:
          description: User who created this
          type: string
          example: '1'
          x-mappedTo: CREATEDBY
          readOnly: true
        modifiedBy:
          description: User who modified this
          type: string
          example: '95'
          x-mappedTo: MODIFIEDBY
          readOnly: true
      readOnly: true
    contract-schedule-line-typeref.s1.schema:
      type: object
      title: contract-schedule-line
      required:
        - scheduledAmount
      properties:
        key:
          type: string
          description: Schedule line system-assigned key.
          x-mappedTo: RECORDNO
          readOnly: true
          example: '145'
        id:
          type: string
          description: Schedule line unique identifier.
          x-mappedTo: RECORDNO
          x-mutable: false
          example: '145'
        scheduledOperationKey:
          type: string
          x-mappedTo: SCHOPKEY
          description: Scheduled operation key for the associated offline operation.
          example: '57665'
          read-only: true
        status:
          type: string
          description: Schedule line status.
          x-mappedTo: STATE
          readOnly: true
          example: posted
          enum:
            - open
            - terminated
            - posted
            - onHold
          x-mappedToValues:
            - Open
            - Terminated
            - Posted
            - On Hold
        scheduledAmount:
          type: string
          description: Schedule line scheduled amount.
          x-mappedTo: AMOUNT
          format: decimal-precision-2
          example: '125.27'
          nullable: false
        scheduledBaseAmount:
          type: string
          description: Schedule line scheduled base amount.
          x-mappedTo: BASEAMOUNT
          format: decimal-precision-2
          example: '137.52'
        scheduledExchangeRate:
          type: string
          description: Schedule line scheduled exchange rate.
          x-mappedTo: EXCHANGE_RATE
          format: decimal-precision-12
          example: '1.345'
        isHistorical:
          type: boolean
          description: Schedule line historical flag indicating the line was added during initial implementation for historical purposes.
          x-mappedTo: HISTORICAL
          readOnly: true
          example: false
        audit:
          $ref: '#/components/schemas/audit.s1.schema'
      examples: []
    contract-schedule-line-postable-typeref.s1.schema:
      type: object
      title: contract-schedule-line-postable
      required:
        - scheduledPostingDate
      properties:
        scheduledPostingDate:
          type: string
          description: Schedule line scheduled posting date.
          x-mappedTo: POSTINGDATE
          format: date
          example: '2022-04-30'
          nullable: false
        posted:
          type: boolean
          description: Schedule line posted flag.
          x-mappedTo: POSTED
          readOnly: true
          example: false
        actualPostingDate:
          type: string
          description: Schedule line actual posting date.
          x-mappedTo: ACTUALPOSTINGDATE
          readOnly: true
          format: date
          example: '2022-04-30'
        journalEntry:
          type: object
          x-object: journal-entry
          properties:
            key:
              type: string
              description: Journal entry key.
              x-mappedTo: GLBATCHKEY
              readOnly: true
              example: 8153
            id:
              type: string
              description: Journal entry ID.
              x-mappedTo: GLBATCHNO
              readOnly: true
              example: 4765
            href:
              type: string
              description: Journal entry URL.
              readOnly: true
              example: /objects/journal-entry/1981
      examples: []
