openapi: 3.0.0
info:
  title: revenue-template
  description: revenue-template API
  version: '1.0'
  contact:
    name: Niraj Singh
    email: niraj.kumar@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: Revenue templates
    description: A revenue template defines the revenue recognition schedule for the flat/fixed amount associated with a contract line.
paths:
  /objects/revenue-template:
    get:
      summary: List revenue templates
      description: Returns a collection with a key, ID, and link for each revenue template.
      tags:
        - Revenue templates
      operationId: get-objects-revenue-template
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of revenue-template objects
                properties:
                  ia::result:
                    type: array
                    items:
                      $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-pages.schema'
              examples:
                List of revenue templates:
                  value:
                    ia::result:
                      - key: '26'
                        id: Evergreen Revenue
                        href: /objects/revenue-template/26
                      - key: '18'
                        id: Conprjobserved%compA
                        href: /objects/revenue-template/18
                    ia::meta:
                      totalCount: 2
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a/an revenue template
      description: Creates a new revenue template.
      tags:
        - Revenue templates
      operationId: post-objects-revenue-template
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/revenue-template.s1.schema'
                - $ref: '#/components/schemas/revenue-templateRequiredProperties'
            examples:
              Creates a/an revenue template: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New revenue-template
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                New revenue template: {}
        '400':
          $ref: '#/components/responses/400error'
  /objects/revenue-template/{key}:
    parameters:
      - name: key
        description: System-assigned key for the revenue template.
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a/an revenue template
      description: Returns detailed information for a particular revenue template.
      tags:
        - Revenue templates
      operationId: get-objects-revenue-template-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the revenue-template
                properties:
                  ia::result:
                    $ref: '#/components/schemas/revenue-template.s1.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Details of the revenue template:
                  value:
                    ia::result:
                      key: '26'
                      id: Evergreen Revenue
                      description: System generated evergreen revrec template
                      scheduleperiod: monthly
                      postingDay: '1'
                      method: straightLine
                      source: estimatedHours
                      steptemplate: false
                      resumeoption: ''
                      postingtype: automatic
                      status: active
                      audit:
                        modifiedDateTime: '2022-04-22T05:17:12Z'
                        createdDateTime: '2022-04-22T05:17:12Z'
                        createdBy: '1'
                        modifiedBy: '1'
                      href: /objects/revenue-template/26
                    ia::meta:
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a/an revenue template
      description: Updates an existing revenue template by setting field values. Any fields not provided remain unchanged.
      tags:
        - Revenue templates
      operationId: patch-objects-revenue-template-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/revenue-template.s1.schema'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Updates a/an revenue template: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated revenue-template
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Updated revenue template: {}
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a/an revenue template
      description: Deletes a/an revenue template.
      tags:
        - Revenue templates
      operationId: delete-objects-revenue-template-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    revenue-template:
      $ref: '#/components/schemas/revenue-template.s1.schema'
    revenue-templateRequiredProperties:
      type: object
      required:
        - id
    object-reference.schema:
      title: object-reference
      type: object
      description: Reference Object definition
      properties:
        key:
          type: string
        id:
          type: string
        href:
          type: string
          readOnly: true
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    metadata-pages.schema:
      title: metadata-pages
      description: Meta data for collection response
      type: object
      allOf:
        - $ref: '#/components/schemas/metadata.schema'
        - type: object
          properties:
            start:
              type: integer
              description: Start Element Number
              x-mappedTo: null
              readOnly: true
              example: 1
            pageSize:
              type: integer
              description: Page Size
              x-mappedTo: null
              readOnly: true
              example: 100
            next:
              type: integer
              description: Next Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: 101
            previous:
              type: integer
              description: Previous Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: null
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
    status.s1.schema:
      title: status
      type: string
      enum:
        - active
        - inactive
      x-mappedToValues:
        - active
        - inactive
      description: Object status.
      default: active
      x-mappedTo: STATUS
      example: active
    audit.s1.schema:
      type: object
      title: audit
      properties:
        createdDateTime:
          description: Time of the submission
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENCREATED
          readOnly: true
        modifiedDateTime:
          description: Time of the modification
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENMODIFIED
          readOnly: true
        createdBy:
          description: User who created this
          type: string
          example: '1'
          x-mappedTo: CREATEDBY
          readOnly: true
        modifiedBy:
          description: User who modified this
          type: string
          example: '95'
          x-mappedTo: MODIFIEDBY
          readOnly: true
      readOnly: true
    revenue-template.s1.schema:
      title: revenue-template
      x-mappedTo: contractrevenuetemplate
      type: object
      description: null
      properties:
        key:
          type: string
          description: Revenue Template Key
          readOnly: true
          x-mappedTo: RECORDNO
          example: '2'
        id:
          type: string
          description: Name
          x-mappedTo: NAME
          x-mutable: false
          example: STRAIGHTLINE_MANUAL
        href:
          type: string
          description: URL of the revenue template.
          readOnly: true
          example: /objects/revenue-template/2
        description:
          type: string
          description: Description
          x-mappedTo: DESCRIPTION
          example: STRAIGHTLINE MANUAL
        schedulePeriod:
          type: string
          description: Recognition schedule period
          x-mappedTo: SCHEDULEPERIOD
          enum:
            - monthly
            - quarterly
            - semiAnnually
            - annually
          x-mappedToValues:
            - Monthly
            - Quarterly
            - Semi-annually
            - Annually
          default: Monthly
          example: monthly
        postingDay:
          type: string
          description: Posting day
          x-mappedTo: POSTINGDAY
          enum:
            - '1'
            - '2'
            - '3'
            - '4'
            - '5'
            - '6'
            - '7'
            - '8'
            - '9'
            - '10'
            - '11'
            - '12'
            - '13'
            - '14'
            - '15'
            - '16'
            - '17'
            - '18'
            - '19'
            - '20'
            - '21'
            - '22'
            - '23'
            - '24'
            - '25'
            - '26'
            - '27'
            - '28'
            - '29'
            - '30'
            - '31'
          default: '1'
          example: '2'
        recognitionMethod:
          type: string
          description: Recognition method
          x-mappedTo: METHOD
          enum:
            - straightLine
            - dailyRate
            - quantityBased
            - predefinedPercentages
            - projectPercentComplete
            - taskPercentComplete
          x-mappedToValues:
            - Straight line
            - Daily rate
            - Quantity based
            - Predefined percentages
            - Project percent complete
            - Task percent complete
          default: Straight line
          example: straightLine
        recognitionSource:
          type: string
          description: Recognition method source
          x-mappedTo: SOURCE
          enum:
            - estimatedHours
            - observedPercentCompleted
            - budgetedHours
            - plannedHours
          x-mappedToValues:
            - Estimated hours
            - Observed % completed
            - Budgeted hours
            - Planned hours
          default: Estimated hours
          example: estimatedHours
        isStep:
          type: boolean
          description: Step revenue
          x-mappedTo: STEPTEMPLATE
          x-mappedToType: string
          default: false
          example: false
        defaultPostingType:
          type: string
          description: Default posting type
          x-mappedTo: POSTINGTYPE
          enum:
            - automatic
            - manual
          x-mappedToValues:
            - Automatic
            - Manual
          default: manual
          example: automatic
        resumeAdjustmentOption:
          type: string
          description: Revenue adjustment option
          x-mappedTo: RESUMEOPTION
          enum:
            - oneTime
            - distributed
            - walkForward
          x-mappedToValues:
            - One time
            - Distributed
            - Walk forward
          example: oneTime
        status:
          $ref: '#/components/schemas/status.s1.schema'
        audit:
          $ref: '#/components/schemas/audit.s1.schema'
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
