openapi: 3.0.0
info:
  title: contact-tax-group
  description: contact-tax-group API
  version: '1.0'
  contact:
    email: anjali.israni@sage.com
    name: Anjali Israni
tags:
  - name: Contact tax groups
    description: Contact tax groups enable taxes to be applied to customers, vendors, and their contacts, according to their jurisdictions. Associate customers, vendors, and their contacts with contact tax groups. Then, use tax schedule maps to apply different tax schedules to contact tax groups.
servers:
  - url: 'http://localhost:3000'
paths:
  '/objects/contact-tax-group/{key}':
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
        description: System-assigned key for the contact tax group.
    get:
      summary: Get a contact tax group
      description: Returns detailed information for a specified contact tax group.
      tags:
        - Contact tax groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the contact-tax-group
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/contact-tax-group'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
      operationId: get-objects-contact-tax-group-key
    delete:
      summary: Delete a contact tax group
      description: Deletes a contact tax group.
      tags:
        - Contact tax groups
      operationId: delete-objects-contact-tax-group-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a contact tax group
      description: Updates an existing contact tax group by setting field values. Any fields not provided remain unchanged.
      operationId: patch-objects-contact-tax-group-key
      tags:
        - Contact tax groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated contact-tax-group
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Update a contact tax group:
                  value:
                    'ia::result':
                      key: '1'
                      id: Auto Contact Tax
                      href: /objects/contact-tax-group/1
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/contact-tax-group'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Update a contact tax group:
                value:
                  groupType: contact
                  taxSolution:
                    id: '1'
  /objects/contact-tax-group:
    get:
      summary: List contact tax groups
      description: Returns a collection with a key, ID, and link for each contact tax group. This operation is mostly for use in testing; use query to find objects that meet certain criteria and to specify properties that are returned.
      tags:
        - Contact tax groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of contact-tax-group objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List contact tax groups:
                  value:
                    'ia::result':
                      - key: '1'
                        id: Auto Contact Tax
                        href: /objects/contact-tax-group/1
                      - key: '2'
                        id: Electronic Contact Tax
                        href: /objects/contact-tax-group/2
                      - key: '3'
                        id: Gardening Contact Tax
                        href: /objects/contact-tax-group/3
                    'ia::meta':
                      totalCount: 3
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
      operationId: get-objects-contact-tax-group
    post:
      summary: Create a contact tax group
      description: Creates a new contact tax group.
      tags:
        - Contact tax groups
      operationId: post-objects-contact-tax-group
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New contact-tax-group
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Create a contact tax group:
                  value:
                    'ia::result':
                      key: '1'
                      id: Auto Contact Tax
                      href: /objects/contact-tax-group/1
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/contact-tax-group'
                - $ref: '#/components/schemas/contact-tax-groupRequiredProperties'
            examples:
              Create a contact tax group:
                value:
                  id: Auto Contact Tax
                  groupType: contact
                  taxSolution:
                    id: '1'
components:
  schemas:
    contact-tax-group:
      $ref: ../models/contact-tax-group.s1.schema.yaml
    contact-tax-groupRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
