openapi: 3.0.0
info:
  title: earning-type
  description: earning-type API
  version: '1.0'
  contact:
    email: atul.sadhu@sage.com
    name: Atul Sadhu
tags:
  - name: Earning types
    description: Earning type description -- explain what it's for and how it's used.
servers:
  - url: 'http://localhost:3000'
paths:
  '/objects/earning-type/{key}':
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
        description: System-assigned key for the earning type.
    get:
      summary: Get an earning type
      description: Returns detailed information for a particular earning type.
      tags:
        - Earning types
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/earning-type'
        '400':
          description: Bad Request
      operationId: get-objects-earning-type-key
components:
  schemas:
    earning-type:
      $ref: ../models/earning-type.s1.schema.yaml
