openapi: 3.0.0
info:
  title: Services
  description: Services API OpenAPI Spec
  version: '1.0'
  contact:
    email: anjali.israni@sage.com
    name: Anjali Israni
servers:
  - url: http://localhost:3000
tags:
  - name: Models
    description: Model service
paths:
  /services/model:
    get:
      summary: Get an object model definition
      description: List all the fields and relationships for an object.
      operationId: get-services-model
      tags:
        - Models
      parameters:
        - $ref: '#/components/parameters/name'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Definition of the object model
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-model.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Model for department:
                  value:
                    ia::result:
                      fields:
                        id:
                          mutable: false
                          nullable: false
                          type: string
                          readOnly: false
                          writeOnly: false
                          required: false
                        key:
                          readOnly: true
                          type: string
                          writeOnly: false
                          required: false
                          nullable: false
                          mutable: false
                        name:
                          nullable: false
                          type: string
                          readOnly: false
                          writeOnly: false
                          required: false
                          mutable: true
                        reportTitle:
                          nullable: true
                          type: string
                          readOnly: false
                          writeOnly: false
                          required: false
                          mutable: true
                        status:
                          enum:
                            - active
                            - activeNonPosting
                            - inactive
                          type: string
                          readOnly: false
                          writeOnly: false
                          required: false
                          nullable: false
                          mutable: true
                      groups:
                        audit:
                          fields:
                            createdBy:
                              readOnly: true
                              type: string
                              writeOnly: false
                              required: false
                              nullable: false
                              mutable: false
                            createdDateTime:
                              format: date-time
                              readOnly: true
                              type: string
                              writeOnly: false
                              required: false
                              nullable: false
                              mutable: false
                            modifiedBy:
                              readOnly: true
                              type: string
                              writeOnly: false
                              required: false
                              nullable: false
                              mutable: false
                            modifiedDateTime:
                              format: date-time
                              readOnly: true
                              type: string
                              writeOnly: false
                              required: false
                              nullable: false
                              mutable: false
                      httpMethods: OPTIONS,GET,DELETE,PATCH,POST
                      refs:
                        parent:
                          apiObject: department
                          fields:
                            id:
                              readOnly: true
                              type: string
                              writeOnly: false
                              required: false
                              nullable: false
                              mutable: false
                            key:
                              nullable: true
                              readOnly: false
                              type: string
                              writeOnly: false
                              required: false
                              mutable: true
                            name:
                              readOnly: true
                              type: string
                              writeOnly: false
                              required: false
                              nullable: false
                              mutable: false
                        supervisor:
                          apiObject: employee
                          fields:
                            id:
                              readOnly: true
                              type: string
                              writeOnly: false
                              required: false
                              nullable: false
                              mutable: false
                            key:
                              nullable: true
                              readOnly: false
                              type: string
                              writeOnly: false
                              required: false
                              mutable: true
                            name:
                              readOnly: true
                              type: string
                              writeOnly: false
                              required: false
                              nullable: false
                              mutable: false
                      lists: []
                      idempotenceSupported: true
                    ia::meta:
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
components:
  parameters:
    name:
      name: name
      description: Object name
      in: query
      schema:
        type: string
      required: true
      example: vendor
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
  schemas:
    object-model.schema:
      title: object-model
      type: object
      description: Generic response for object model definition
      properties:
        fields:
          type: object
        groups:
          type: object
        refs:
          type: object
        idempotenceSupported:
          type: boolean
          example: true
          default: true
        httpMethods:
          type: string
          example: OPTIONS,GET,DELETE,PATCH,POST
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
