openapi: 3.0.0
info:
  title: ap-summary
  description: ap-summary API
  version: '1.0'
  contact:
    name: Anjali Israni
    email: anjali.israni@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: AP summaries
    description: AP summary description -- explain what it's for and how it's used.
paths:
  /objects/ap-summary:
    get:
      summary: List AP summaries
      description: Returns a collection with a key, ID, and link for each AP summary.
      tags:
        - AP summaries
      operationId: get-objects-ap-summary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of ap-summary objects
                properties:
                  ia::result:
                    type: array
                    items:
                      $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-pages.schema'
              examples:
                List of AP summaries: {}
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a/an AP summary
      description: Creates a new AP summary.
      tags:
        - AP summaries
      operationId: post-objects-ap-summary
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ap-summary.s1.schema'
                - $ref: '#/components/schemas/ap-summaryRequiredProperties'
            examples:
              Creates a/an AP summary: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New ap-summary
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                New AP summary: {}
        '400':
          $ref: '#/components/responses/400error'
  /objects/ap-summary/{key}:
    parameters:
      - name: key
        description: system-assigned unique key for the AP summary.
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a/an AP summary
      description: Returns detailed information for a particular AP summary.
      tags:
        - AP summaries
      operationId: get-objects-ap-summary-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the ap-summary
                properties:
                  ia::result:
                    $ref: '#/components/schemas/ap-summary.s1.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Details of the AP summary: {}
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a/an AP summary
      description: Updates an existing AP summary by setting field values. Any fields not provided remain unchanged.
      tags:
        - AP summaries
      operationId: patch-objects-ap-summary-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ap-summary.s1.schema'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Updates a/an AP summary: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated ap-summary
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Updated AP summary: {}
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a/an AP summary
      description: Deletes a/an AP summary.
      tags:
        - AP summaries
      operationId: delete-objects-ap-summary-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    ap-summary:
      $ref: '#/components/schemas/ap-summary.s1.schema'
    ap-summaryRequiredProperties:
      type: object
      required:
        - id
    object-reference.schema:
      title: object-reference
      type: object
      description: Reference Object definition
      properties:
        key:
          type: string
        id:
          type: string
        href:
          type: string
          readOnly: true
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    metadata-pages.schema:
      title: metadata-pages
      description: Meta data for collection response
      type: object
      allOf:
        - $ref: '#/components/schemas/metadata.schema'
        - type: object
          properties:
            start:
              type: integer
              description: Start Element Number
              x-mappedTo: null
              readOnly: true
              example: 1
            pageSize:
              type: integer
              description: Page Size
              x-mappedTo: null
              readOnly: true
              example: 100
            next:
              type: integer
              description: Next Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: 101
            previous:
              type: integer
              description: Previous Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: null
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
    status.s1.schema:
      title: status
      type: string
      enum:
        - active
        - inactive
      x-mappedToValues:
        - active
        - inactive
      description: Object status.
      default: active
      x-mappedTo: STATUS
      example: active
    ap-summary.s1.schema:
      title: ap-summary
      x-mappedTo: apbatch
      type: object
      description: Payment batches of all payment processed in the system.
      properties:
        key:
          type: string
          description: Summary Key
          readOnly: true
          x-mappedTo: RECORDNO
          example: null
        id:
          type: string
          description: Summary id
          readOnly: true
          x-mappedTo: RECORDNO
          example: null
        href:
          type: string
          readOnly: true
        name:
          type: string
          description: Summary name
          x-mappedTo: TITLE
          example: null
        createdBy:
          type: string
          description: Created
          x-mappedTo: AUTOCREATED
          example: null
          enum:
            - system
            - manual
          x-mappedToValues:
            - Auto-Summary
            - Manual
          default: manual
        postingDate:
          type: string
          description: GL posting date
          x-mappedTo: CREATED
          example: null
        recordType:
          type: string
          description: Record type
          x-mappedTo: RECORDTYPE
          example: null
        total:
          type: string
          description: Total
          x-mappedTo: TOTAL
          example: null
        state:
          type: string
          description: Open or closed
          x-mappedTo: OPEN
          example: null
          enum:
            - open
            - closed
          x-mappedToValues:
            - Open
            - Closed
        parent:
          type: object
          x-object: ap-summary
          properties:
            key:
              type: string
              description: Parent batch
              x-mappedTo: PARENTKEY
              example: null
            href:
              type: string
              readOnly: true
        preventGLPosting:
          type: boolean
          description: Not for GL posting
          x-mappedTo: NOGL
          example: null
          x-mappedToType: string
        glAccount:
          type: object
          x-object: gl-account
          properties:
            key:
              type: string
              description: Bank account ID
              x-mappedTo: ACCOUNTNOKEY
              example: null
            href:
              type: string
              readOnly: true
        isSystemGenerated:
          type: boolean
          description: System generated
          x-mappedTo: SYSTEMGENERATED
          x-mappedToType: string
          example: null
          default: false
        status:
          $ref: '#/components/schemas/status.s1.schema'
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
