openapi: 3.0.0
info:
  title: order-entry-tax-schedule-detail
  description: Order Entry Tax Schedule Detail is used to associate a tax detail to the date at which the tax detail becomes effective.
  version: '1.0'
  contact:
    name: Carolyn Philip
    email: carolyn.philip@sage.com
tags:
  - name: Order Entry tax schedule details
    description: Order Entry tax schedule detail description -- explain what it's for and how it's used.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/order-entry-tax-schedule-detail:
    get:
      summary: List Order Entry tax schedule details
      description: 'Returns a collection with a key, ID, and link for each Order Entry tax schedule detail.'
      tags:
        - Order Entry tax schedule details
      operationId: get-objects-order-entry-tax-schedule-detail
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of order-entry-tax-schedule-detail objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List of Order Entry tax schedule details:
                  value:
                    'ia::result':
                      - key: '8'
                        id: '8'
                        href: /objects/order-entry-tax-schedule-detail/8
                      - key: '9'
                        id: '9'
                        href: /objects/order-entry-tax-schedule-detail/9
                      - key: '10'
                        id: '10'
                        href: /objects/order-entry-tax-schedule-detail/10
                    'ia::meta':
                      totalCount: 3
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
  '/objects/order-entry-tax-schedule-detail/{key}':
    parameters:
      - name: key
        description: System-assigned key for the Order Entry tax schedule detail.
        in: path
        required: true
        schema:
          type: string
          default: '162'
          example: '162'
    get:
      summary: Get a/an Order Entry tax schedule detail
      description: Returns detailed information for a particular Order Entry tax schedule detail.
      tags:
        - Order Entry tax schedule details
      operationId: get-objects-order-entry-tax-schedule-detail-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the order-entry-tax-schedule-detail
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/order-entry-tax-schedule-detail'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Details of the Order Entry tax schedule detail:
                  value:
                    'ia::result':
                      taxSchedule:
                        key: '162'
                        id: '162'
                        name: Tax Florida
                        href: /objects/order-entry-tax-schedule/162
                      key: '44'
                      id: '44'
                      taxDetail:
                        id: Sales Tax California
                        key: '22'
                        href: /objects/order-entry-tax-detail/22
                      effectiveDate: '2022-02-03'
                      href: /objects/order-entry-tax-schedule-detail/44
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    order-entry-tax-schedule-detail:
      $ref: ../models/order-entry-tax-schedule-detail.s1.schema.yaml
    order-entry-tax-schedule-detailRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
