openapi: 3.0.0
info:
  title: position-skill
  description: position-skill API
  version: '1.0'
  contact:
    name: Dylan Holt
    email: dylan.holt@sage.com
tags:
  - name: Position skills
    description: Position skill description -- explain what it's for and how it's used.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/position-skill:
    get:
      summary: List position skills
      description: Returns a collection with a key, ID, and link for each position skill.
      tags:
        - Position skills
      operationId: get-objects-position-skill
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of position-skill objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List of position skills: {}
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a position skill
      description: Creates a new position skill.
      tags:
        - Position skills
      operationId: post-objects-position-skill
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/position-skill'
                - $ref: '#/components/schemas/position-skillRequiredProperties'
            examples:
              Creates a position skill: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New position-skill
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                New position skill: {}
        '400':
          $ref: '#/components/responses/400error'
  '/objects/position-skill/{key}':
    parameters:
      - name: key
        description: system-assigned unique key for the position skill.
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a/an position skill
      description: Returns detailed information for a particular position skill.
      tags:
        - Position skills
      operationId: get-objects-position-skill-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the position-skill
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/position-skill'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Details of the position skill: {}
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a/an position skill
      description: Updates an existing position skill by setting field values. Any fields not provided remain unchanged.
      tags:
        - Position skills
      operationId: patch-objects-position-skill-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/position-skill'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Updates a/an position skill: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated position-skill
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Updated position skill: {}
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a position skill
      description: Deletes a position skill.
      tags:
        - Position skills
      operationId: delete-objects-position-skill-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    position-skill:
      $ref: ../models/position-skill.s1.schema.yaml
    position-skillRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml