openapi: 3.0.0
info:
  title: project-resource
  description: project-resource API
  version: '1.0'
  contact:
    name: Tim Miller
    email: tim.miller@sage.com
tags:
  - name: Project resource
    description: Project resource description -- explain what it's for and how it's used.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/project-resource:
    get:
      summary: List project resources
      description: Returns a collection with a key, ID, and link for each project resource.
      tags:
        - Project resource
      operationId: get-objects-project-resource
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of project-resource objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List of project resource: {}
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a/an project resource
      description: Creates a new project resource.
      tags:
        - Project resource
      operationId: post-objects-project-resource
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/project-resource'
                - $ref: '#/components/schemas/project-resourceRequiredProperties'
            examples:
              Creates a/an project resource: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New project-resource
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                New project resource: {}
        '400':
          $ref: '#/components/responses/400error'
  '/objects/project-resource/{key}':
    parameters:
      - name: key
        description: system-assigned unique key for the project resource.
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a/an project resource
      description: Returns detailed information for a particular project resource.
      tags:
        - Project resource
      operationId: get-objects-project-resource-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the project-resource
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/project-resource'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Details of the project resource: {}
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a/an project resource
      description: Updates an existing project resource by setting field values. Any fields not provided remain unchanged.
      tags:
        - Project resource
      operationId: patch-objects-project-resource-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/project-resource'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Updates a/an project resource: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated project-resource
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Updated project resource: {}
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a/an project resource
      description: Deletes a/an project resource.
      tags:
        - Project resource
      operationId: delete-objects-project-resource-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    project-resource:
      $ref: ../models/project-resource.s1.schema.yaml
    project-resourceRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
