openapi: 3.0.0
info:
  title: db-server-throttle
  description: db-server-throttle API
  version: '1.0'
  contact:
    name: Anjali Israni
    email: anjali.israni@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: Db server throttle
    description: Db server throttle description -- explain what it's for and how it's used.
paths:
  /objects/db-server-throttle:
    get:
      summary: List db server throttles
      description: Returns a collection with a key, ID, and link for each db server throttle.
      tags:
        - Db server throttle
      operationId: get-objects-db-server-throttle
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of db-server-throttle objects
                properties:
                  ia::result:
                    type: array
                    items:
                      $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-pages.schema'
              examples:
                List of db server throttle:
                  value:
                    ia::result:
                      - key: '90'
                        id: dev02
                        href: /objects/db-server-throttle/90
                      - key: '24'
                        id: dev08
                        href: /objects/db-server-throttle/24
                      - key: '81'
                        id: dev25
                        href: /objects/db-server-throttle/81
                    ia::meta:
                      totalCount: 3
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a/an db server throttle
      description: Creates a new db server throttle.
      tags:
        - Db server throttle
      operationId: post-objects-db-server-throttle
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/db-server-throttle.s1.schema'
                - $ref: '#/components/schemas/db-server-throttleRequiredProperties'
            examples:
              Creates a/an db server throttle: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New db-server-throttle
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                New db server throttle: {}
        '400':
          $ref: '#/components/responses/400error'
  /objects/db-server-throttle/{key}:
    parameters:
      - name: key
        description: system-assigned unique key for the db server throttle.
        in: path
        required: true
        schema:
          type: string
          example: '90'
    get:
      summary: Get a/an db server throttle
      description: Returns detailed information for a particular db server throttle.
      tags:
        - Db server throttle
      operationId: get-objects-db-server-throttle-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the db-server-throttle
                properties:
                  ia::result:
                    $ref: '#/components/schemas/db-server-throttle.s1.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Details of the db server throttle:
                  value:
                    ia::result:
                      key: '90'
                      id: dev02
                      limit: 80
                      override:
                        limit: null
                        endDate: null
                      notes: null
                      status: active
                      audit:
                        createdDateTime: '2023-03-30T23:58:36Z'
                        modifiedDateTime: '2023-03-30T23:58:36Z'
                      href: /objects/db-server-throttle/90
                    ia::meta:
                      totalCount: 1
                      totalSuccess: 1
                      totalError: 0
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a/an db server throttle
      description: Updates an existing db server throttle by setting field values. Any fields not provided remain unchanged.
      tags:
        - Db server throttle
      operationId: patch-objects-db-server-throttle-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/db-server-throttle.s1.schema'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Updates a/an db server throttle: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated db-server-throttle
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Updated db server throttle: {}
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a/an db server throttle
      description: Deletes a/an db server throttle.
      tags:
        - Db server throttle
      operationId: delete-objects-db-server-throttle-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    db-server-throttle:
      $ref: '#/components/schemas/db-server-throttle.s1.schema'
    db-server-throttleRequiredProperties:
      type: object
      required:
        - id
    object-reference.schema:
      title: object-reference
      type: object
      description: Reference Object definition
      properties:
        key:
          type: string
        id:
          type: string
        href:
          type: string
          readOnly: true
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    metadata-pages.schema:
      title: metadata-pages
      description: Meta data for collection response
      type: object
      allOf:
        - $ref: '#/components/schemas/metadata.schema'
        - type: object
          properties:
            start:
              type: integer
              description: Start Element Number
              x-mappedTo: null
              readOnly: true
              example: 1
            pageSize:
              type: integer
              description: Page Size
              x-mappedTo: null
              readOnly: true
              example: 100
            next:
              type: integer
              description: Next Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: 101
            previous:
              type: integer
              description: Previous Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: null
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
    status.s1.schema:
      title: status
      type: string
      enum:
        - active
        - inactive
      x-mappedToValues:
        - active
        - inactive
      description: Object status.
      default: active
      x-mappedTo: STATUS
      example: active
    db-server-throttle.s1.schema:
      title: db-server-throttle
      x-mappedTo: dbserverthrottle
      type: object
      description: null
      properties:
        key:
          type: string
          description: System-assigned key for the db server throttle limit.
          readOnly: true
          x-mappedTo: RECORDNO
          example: '23'
        id:
          type: string
          description: Unique identifier for db server throttle limit
          x-mappedTo: DBSERVER
          example: dbserver1
        href:
          type: string
          description: Endpoint for the db server throttle limit.
          readOnly: true
          example: /objects/db-server-throttle/23
        limit:
          type: integer
          description: Throttle limit.
          x-mappedTo: THROTTLE_LIMIT
          example: 20
        notes:
          type: string
          x-mappedTo: NOTES
          description: Notes or comments
          example: Limit override for customer escalation resolution
        override:
          type: object
          properties:
            limit:
              type: integer
              x-mappedTo: THROTTLE_LIMIT_OVERRIDE
              description: Override the throttle limit
              example: 200
            endDate:
              type: string
              format: date
              x-mappedTo: END_DATE
              description: End data for throttle Limit overide
              example: '2023-10-10'
        status:
          $ref: '#/components/schemas/status.s1.schema'
        audit:
          type: object
          properties:
            createdDateTime:
              description: Time of the submission
              type: string
              format: date-time
              example: '2022-04-20T16:20:00Z'
              x-mappedTo: WHENCREATED
              readOnly: true
            modifiedDateTime:
              description: Time of the modification
              type: string
              format: date-time
              example: '2022-04-20T16:20:00Z'
              x-mappedTo: WHENMODIFIED
              readOnly: true
          readOnly: true
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
