openapi: 3.0.0
info:
  title: contact-tax-group
  description: contact-tax-group API
  version: '1.0'
  contact:
    email: anjali.israni@sage.com
    name: Anjali Israni
servers:
  - url: http://localhost:3000
tags:
  - name: Contact tax groups
    description: Contact tax groups enable taxes to be applied to customers, vendors, and their contacts, according to their jurisdictions. Associate customers, vendors, and their contacts with contact tax groups. Then, use tax schedule maps to apply different tax schedules to contact tax groups.
paths:
  /objects/contact-tax-group/{key}:
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
        description: System-assigned key for the contact tax group.
    get:
      summary: Get a contact tax group
      description: Returns detailed information for a specified contact tax group.
      tags:
        - Contact tax groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the contact-tax-group
                properties:
                  ia::result:
                    $ref: '#/components/schemas/contact-tax-group.s1.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
      operationId: get-objects-contact-tax-group-key
    delete:
      summary: Delete a contact tax group
      description: Deletes a contact tax group.
      tags:
        - Contact tax groups
      operationId: delete-objects-contact-tax-group-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a contact tax group
      description: Updates an existing contact tax group by setting field values. Any fields not provided remain unchanged.
      operationId: patch-objects-contact-tax-group-key
      tags:
        - Contact tax groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated contact-tax-group
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Update a contact tax group:
                  value:
                    ia::result:
                      key: '1'
                      id: Auto Contact Tax
                      href: /objects/contact-tax-group/1
                    ia::meta:
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/contact-tax-group.s1.schema'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Update a contact tax group:
                value:
                  groupType: contact
                  taxSolution:
                    id: '1'
  /objects/contact-tax-group:
    get:
      summary: List contact tax groups
      description: Returns a collection with a key, ID, and link for each contact tax group. This operation is mostly for use in testing; use query to find objects that meet certain criteria and to specify properties that are returned.
      tags:
        - Contact tax groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of contact-tax-group objects
                properties:
                  ia::result:
                    type: array
                    items:
                      $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-pages.schema'
              examples:
                List contact tax groups:
                  value:
                    ia::result:
                      - key: '1'
                        id: Auto Contact Tax
                        href: /objects/contact-tax-group/1
                      - key: '2'
                        id: Electronic Contact Tax
                        href: /objects/contact-tax-group/2
                      - key: '3'
                        id: Gardening Contact Tax
                        href: /objects/contact-tax-group/3
                    ia::meta:
                      totalCount: 3
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
      operationId: get-objects-contact-tax-group
    post:
      summary: Create a contact tax group
      description: Creates a new contact tax group.
      tags:
        - Contact tax groups
      operationId: post-objects-contact-tax-group
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New contact-tax-group
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Create a contact tax group:
                  value:
                    ia::result:
                      key: '1'
                      id: Auto Contact Tax
                      href: /objects/contact-tax-group/1
                    ia::meta:
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/contact-tax-group.s1.schema'
                - $ref: '#/components/schemas/contact-tax-groupRequiredProperties'
            examples:
              Create a contact tax group:
                value:
                  id: Auto Contact Tax
                  groupType: contact
                  taxSolution:
                    id: '1'
components:
  schemas:
    contact-tax-group:
      $ref: '#/components/schemas/contact-tax-group.s1.schema'
    contact-tax-groupRequiredProperties:
      type: object
      required:
        - id
    audit.s1.schema:
      type: object
      title: audit
      properties:
        createdDateTime:
          description: Time of the submission
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENCREATED
          readOnly: true
        modifiedDateTime:
          description: Time of the modification
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENMODIFIED
          readOnly: true
        createdBy:
          description: User who created this
          type: string
          example: '1'
          x-mappedTo: CREATEDBY
          readOnly: true
        modifiedBy:
          description: User who modified this
          type: string
          example: '95'
          x-mappedTo: MODIFIEDBY
          readOnly: true
      readOnly: true
    contact-tax-group.s1.schema:
      title: contact-tax-group
      type: object
      description: Contact tax groups enable taxes to be applied to customers, vendors, and their contacts, according to their jurisdictions.
      x-mappedTo: taxgroup
      properties:
        key:
          type: string
          description: System-assigned key for the contact tax group.
          x-mappedTo: RECORDNO
          readOnly: true
        id:
          type: string
          description: Unique name for the contact tax group.
          x-mappedTo: NAME
          x-mutable: false
        href:
          type: string
          description: URL for the contact tax group.
          readOnly: true
        groupType:
          type: string
          enum:
            - contact
          x-mappedToValues:
            - Contact
          description: Tax group type.
          x-mappedTo: GROUPTYPE
        taxSolution:
          type: object
          description: Tax solution associated with this contact tax group. Different tax solutions are available for different countries, for example, Australia GST, South Africa VAT, UK Vat.
          x-object: tax-solution
          x-mappedTo: TAXSOLUTION
          properties:
            key:
              type: string
              description: System-assigned key for the tax solution.
              x-mappedTo: TAXSOLUTIONKEY
            id:
              type: string
              description: ID for the tax solution.
              x-mappedTo: TAXSOLUTIONID
            href:
              type: string
              description: URL for the tax solution.
              readOnly: true
        audit:
          $ref: '#/components/schemas/audit.s1.schema'
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
    object-reference.schema:
      title: object-reference
      type: object
      description: Reference Object definition
      properties:
        key:
          type: string
        id:
          type: string
        href:
          type: string
          readOnly: true
    metadata-pages.schema:
      title: metadata-pages
      description: Meta data for collection response
      type: object
      allOf:
        - $ref: '#/components/schemas/metadata.schema'
        - type: object
          properties:
            start:
              type: integer
              description: Start Element Number
              x-mappedTo: null
              readOnly: true
              example: 1
            pageSize:
              type: integer
              description: Page Size
              x-mappedTo: null
              readOnly: true
              example: 100
            next:
              type: integer
              description: Next Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: 101
            previous:
              type: integer
              description: Previous Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: null
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
