openapi: 3.0.0
info:
  title: earning-type
  description: earning-type API
  version: '1.0'
  contact:
    email: atul.sadhu@sage.com
    name: Atul Sadhu
servers:
  - url: http://localhost:3000
tags:
  - name: Earning types
    description: Earning type description -- explain what it's for and how it's used.
paths:
  /objects/earning-type/{key}:
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
        description: System-assigned key for the earning type.
    get:
      summary: Get an earning type
      description: Returns detailed information for a particular earning type.
      tags:
        - Earning types
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/earning-type.s1.schema'
        '400':
          description: Bad Request
      operationId: get-objects-earning-type-key
components:
  schemas:
    earning-type:
      $ref: '#/components/schemas/earning-type.s1.schema'
    audit.s1.schema:
      type: object
      title: audit
      properties:
        createdDateTime:
          description: Time of the submission
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENCREATED
          readOnly: true
        modifiedDateTime:
          description: Time of the modification
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENMODIFIED
          readOnly: true
        createdBy:
          description: User who created this
          type: string
          example: '1'
          x-mappedTo: CREATEDBY
          readOnly: true
        modifiedBy:
          description: User who modified this
          type: string
          example: '95'
          x-mappedTo: MODIFIEDBY
          readOnly: true
      readOnly: true
    earning-type.s1.schema:
      title: earning-type
      x-mappedTo: earningtype
      type: object
      description: List of the Earning types
      properties:
        key:
          type: string
          description: Earning Type Key
          x-mappedTo: RECORDNO
        id:
          type: string
          description: Earning Type Name
          x-mappedTo: NAME
          x-mutable: false
        name:
          type: string
          description: Earning Type Name
          x-mappedTo: NAME
        audit:
          $ref: '#/components/schemas/audit.s1.schema'
