openapi: 3.0.0
info:
  title: preferences.multi-entity
  description: preferences.multi-entity API
  version: '1.0'
  contact:
    name: Girish Dhareshwar
    email: Girish.dhareshwar@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: Multi-entity preferences
    description: In a multi-entity shared company, entities represent a separate tax identification or a separately secured, fully balancing set of books. Entities typically represent divisions, franchises, affiliates, associations, locations, chapters, self-balancing funds, or subsidiaries, with a shared chart of accounts.
paths:
  /services/preferences/multi-entity:
    get:
      summary: Get multi-entity preferences
      description: Returns current multi entity preference settings.
      tags:
        - Multi-entity preferences
      operationId: get-services-preferences.multi-entity
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Multi-entity preferences
                properties:
                  ia::result:
                    type: array
                    items:
                      $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-pages.schema'
              examples:
                Current multi-entity preferences:
                  value:
                    ia::result:
                      enableMultipleBaseCurrency: true
                      approvalCurrency: CAD
                      isForm1099: false
                      restrictions:
                        disableEntitySlideIn: false
                        restrictSubledgerTxnToEntity: false
                        enableCustomerRestrictions: true
                        enableVendorRestrictions: true
                        enableCheckingAccountRestrictions: false
                        enableSavingsAccountRestrictions: false
                      interEntityAccountMappingPlan: basic
                      interEntityTransactions:
                        enableForJournalEntry: true
                        manuallyBalanceSubledgerTxns: false
                        manuallyBalanceSubledgerCredits: true
                        creditsJournal:
                          key: '10'
                          id: IEP
                          name: Inter Entity Payable
                          href: /objects/gl-journal/10
                      balanceJournalEntryBy: entity
                      limitAPCredit: true
                      limitARCredit: false
                      moduleConfigured: true
                      audit:
                        createdDateTime: '2021-10-29T08:00:50Z'
                        modifiedDateTime: '2021-12-01T09:08:17Z'
                        createdBy: '1'
                        modifiedBy: '1'
                      href: /services/preferences/multi-entity
                    ia::meta:
                      totalCount: 1,
                      totalSuccess: 1,
                      totalError: 0
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update multi-entity preferences
      description: Update the multi-entity preferences for a company. Any fields not provided remain unchanged.
      tags:
        - Multi-entity preferences
      operationId: patch-services-preferences.multi-entity
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/preferences.multi-entity.s1.schema'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Enable checking account restrictions:
                value:
                  restrictions:
                    enableCheckingAccountRestrictions: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated preferences.multi-entity
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
components:
  schemas:
    preferences.multi-entity:
      $ref: '#/components/schemas/preferences.multi-entity.s1.schema'
    object-reference.schema:
      title: object-reference
      type: object
      description: Reference Object definition
      properties:
        key:
          type: string
        id:
          type: string
        href:
          type: string
          readOnly: true
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    metadata-pages.schema:
      title: metadata-pages
      description: Meta data for collection response
      type: object
      allOf:
        - $ref: '#/components/schemas/metadata.schema'
        - type: object
          properties:
            start:
              type: integer
              description: Start Element Number
              x-mappedTo: null
              readOnly: true
              example: 1
            pageSize:
              type: integer
              description: Page Size
              x-mappedTo: null
              readOnly: true
              example: 100
            next:
              type: integer
              description: Next Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: 101
            previous:
              type: integer
              description: Previous Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: null
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
    audit.s1.schema:
      type: object
      title: audit
      properties:
        createdDateTime:
          description: Time of the submission
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENCREATED
          readOnly: true
        modifiedDateTime:
          description: Time of the modification
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENMODIFIED
          readOnly: true
        createdBy:
          description: User who created this
          type: string
          example: '1'
          x-mappedTo: CREATEDBY
          readOnly: true
        modifiedBy:
          description: User who modified this
          type: string
          example: '95'
          x-mappedTo: MODIFIEDBY
          readOnly: true
      readOnly: true
    preferences.multi-entity.s1.schema:
      title: preferences.multi-entity
      x-mappedTo: mesetup
      type: object
      description: Multi Entity Console Setup object
      properties:
        enableMultipleBaseCurrency:
          type: boolean
          description: Set to `true` to enable each entity to use its own base currency. Multi-currency management must be enabled in the General Ledger.
          x-mappedTo: ENTITYBASECURRENCY
          x-mappedToType: string
          nullable: false
          default: false
        approvalCurrency:
          type: string
          description: Value approval currency for purchase transactions and expense reports. A value approval currency enables Sage Intacct to translate the transaction currency into a common currency, which is used to evaluate transaction approval thresholds and determine whether a transaction requires approval.
          x-mappedTo: APPROVALCURRENCY
        isForm1099:
          type: boolean
          description: Set to `true` to print 1099s with entity-level information, rather than top-level company information. Set to `false` to have the top level company to print a single set of 1099s across all entities and all vendors.
          x-mappedTo: FORM1099
          x-mappedToType: string
          nullable: false
          default: false
        restrictions:
          type: object
          properties:
            disableEntitySlideIn:
              type: boolean
              description: Set to `true` to restrict users to accessing the top level only. Only applies to multi-entity companies with a single base currency
              x-mappedTo: DISABLEENTITYSLIDEIN
              x-mappedToType: string
              nullable: false
              default: false
            restrictSubledgerTxnToEntity:
              type: boolean
              description: Set to `true` to restrict users to entering subledger transactions at the entity level only.
              x-mappedTo: ENTITYONLYTRANS
              x-mappedToType: string
              nullable: false
              default: false
            enableCustomerRestrictions:
              type: boolean
              description: Set to `true` to enable the option to restrict which locations and departments can work with each top-level customer.
              x-mappedTo: ENABLEMULTIOWNCUSTOMER
              x-mappedToType: string
              nullable: false
              default: false
            enableVendorRestrictions:
              type: boolean
              description: Set to `true` to enable the option to restrict which locations and departments can work with each top-level vendor.
              x-mappedTo: ENABLEMULTIOWN
              x-mappedToType: string
              nullable: false
              default: false
            enableCheckingAccountRestrictions:
              type: boolean
              description: Set to `true` to enable the option to restrict which locations and departments can work with each checking account.
              x-mappedTo: ENABLEMULTIOWNCHECKINGAC
              x-mappedToType: string
              nullable: false
              default: false
            enableSavingsAccountRestrictions:
              type: boolean
              description: Set to `true` to enable the option to restrict which locations and departments can work with each savings account.
              x-mappedTo: ENABLEMULTIOWNSAVINGAC
              x-mappedToType: string
              nullable: false
              default: false
        interEntityAccountMappingPlan:
          type: string
          description: |
            Type of inter-entity account mapping:

            * `basic`: Use only one set of inter-entity accounts per entity.
            * `advanced`: Define separate sets of inter-entity accounts for each entity relationship, or entity pair. 
          enum:
            - basic
            - advanced
          x-mappedToValues:
            - Basic
            - Advanced
          x-mappedTo: IEACCTMAPPLAN
          nullable: false
          default: basic
        limitAPCredit:
          type: boolean
          description: |
            Whether AP credits are limited to the owning entity.

            * `false` - Credits are applied to the owning entity first, and then applied from the oldest to the newest invoices.
            * `true` - Limit credits to just the owning entity. Credits are applied to the bills of the owning entity and no others; any remaining credit is reserved for more bills owned by that entity. 
          x-mappedTo: AP_LIMITCREDIT
          x-mappedToType: string
          nullable: false
          default: false
        limitARCredit:
          type: boolean
          description: |
            Whether AR credits are limited to the owning entity.

            * `false` - Credits are applied to the owning entity first, and then applied from the oldest to the newest invoices.
            * `true` - Limit credits to just the owning entity. Credits are applied to the bills of the owning entity and no others; any remaining credit is reserved for more bills owned by that entity. 
          x-mappedTo: AR_LIMITCREDIT
          x-mappedToType: string
          nullable: false
          default: false
        isModuleConfigured:
          type: boolean
          description: Is module configured?
          enum:
            - true
            - false
          x-mappedToValues:
            - T
            - F
          x-mappedTo: MODULE_CONFIGURED
          default: true
          readOnly: true
          x-mappedToType: string
        interEntityTxns:
          type: object
          description: Use these settings to control how Sage Intacct records transactions that involve two or more entities.
          properties:
            enableForJournalEntry:
              type: boolean
              description: |
                Set to `true` to have Intacct automatically create offsetting entries for journal entries that involve two or more entities. Set to `false` to require all balancing line items to be entered manually.

                Note: This option is incompatible with the __Enable journal entry auto-balancing__ option on the Configuration page for General Ledger, which automatically balances GL journal entries using the specified GL auto-balancing account.
              x-mappedTo: ENABLEAUTOIETJE
              x-mappedToType: string
              nullable: false
              default: false
            manuallyBalanceSubledgerTxns:
              type: boolean
              description: |
                Set to `true` to disable automatic tracking of inter-entity payables and receivables for  transactions. For example, although one entity can still pay a bill on behalf of another entity, Intacct will not track the inter-entity payables and receivables by creating offsetting journal entries in the affected entities.

                Setting this to `true` disables inter-entity transactions, and you do not need to specify a `creditsJournal`.
              x-mappedTo: DISABLEIETFINACCT
              x-mappedToType: string
              nullable: false
              default: false
            manuallyBalanceSubledgerCredits:
              type: boolean
              description: |
                Set to `true` to turn off the automatic recording of inter-entity payables and receivables for credits, adjustments, and advances. Intacct won't automatically track the inter-entity payables and receivables by creating offsetting journal entries in the affected entities. 

                You do not need to specify a `creditsJournal` when this field is enabled.
              x-mappedTo: DISABLEIETCRAPP
              x-mappedToType: string
              nullable: false
              default: false
            creditsJournal:
              type: object
              description: The journal to use when posting inter-entity credit bills or invoices to AP or AR, respectively. This journal is used when credits are applied to AR invoices or AP bills that generate an inter-entity transaction (IET) with no source payment record.
              x-object: gl-journal
              x-mappedTo: pe_journal
              properties:
                key:
                  type: string
                  description: System-assigned unique identifier for the credits journal.
                  x-mappedTo: PE_JOURNALKEY
                  readOnly: true
                id:
                  type: string
                  description: ID of the credits journal.
                  x-mappedTo: PE_JOURNAL
                name:
                  type: string
                  description: Name of the credits journal
                  x-mappedTo: PE_JOURNALNAME
                href:
                  type: string
                  description: Endpoint of the credits journal.
                  readOnly: true
        balanceJournalEntryBy:
          type: string
          description: Enforce journal entry balancing by location or entity. If you choose not to enable inter-entity transactions, you can enforce journal entry balancing by location instead of entity.
          enum:
            - location
            - entity
          x-mappedToValues:
            - Location
            - Entity
          x-mappedTo: BALANCE_ENTRY_LOC
          nullable: false
          default: entity
        audit:
          $ref: '#/components/schemas/audit.s1.schema'
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
