openapi: 3.0.0
info:
  title: reporting-period
  description: reporting-period API
  version: '1.0'
  contact:
    name: Tatiana Golovina
    email: tatiana.golovina@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: Reporting periods
    description: Reporting periods are used when creating reports and budgets, and when opening and closing books. They limit the information in a report to specific time ranges.
paths:
  /objects/reporting-period:
    get:
      summary: List reporting periods
      description: Returns up to 100 reporting periods from the collection with a key, ID, and link for each period. This operation is mostly for use in testing; use the query service to find reporting periods that meet specific criteria and to specify the properties that you want in the response.
      tags:
        - Reporting periods
      operationId: get-objects-reporting-period
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of reporting-period objects
                properties:
                  ia::result:
                    type: array
                    items:
                      $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-pages.schema'
              examples:
                List reporting periods:
                  value:
                    ia::result:
                      - key: '1'
                        id: '1'
                        href: /objects/reporting-period/1
                      - key: '2'
                        id: '2'
                        href: /objects/reporting-period/2
                    ia::meta:
                      totalCount: 2
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a reporting period
      description: Creates a new reporting period.
      tags:
        - Reporting periods
      operationId: post-objects-reporting-period
      requestBody:
        description: Reporting period to create
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/reporting-period.s1.schema'
                - $ref: '#/components/schemas/reporting-periodRequiredProperties'
            examples:
              Create a reporting period: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New reporting period
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                New reporting period created:
                  value:
                    ia::result:
                      key: '22'
                      id: '22'
                      href: /objects/reporting-period/1
                    ia::meta:
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
  /objects/reporting-period/{key}:
    parameters:
      - name: key
        description: System-assigned unique key for the reporting period.
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a reporting period
      description: Returns detailed information for a specified reporting period.
      tags:
        - Reporting periods
      operationId: get-objects-reporting-period-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the reporting period
                properties:
                  ia::result:
                    $ref: '#/components/schemas/reporting-period.s1.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Details of the reporting period: {}
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a reporting period
      description: Updates an existing reporting period by setting field values. Any fields not provided remain unchanged.
      tags:
        - Reporting periods
      operationId: patch-objects-reporting-period-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/reporting-period.s1.schema'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Updates a reporting period: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated reporting-period
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Reporting period updated:
                  value:
                    ia::result:
                      key: '312'
                      id: '312'
                      href: /objects/reporting-period/312
                    ia::meta:
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a reporting period
      description: Deletes a reporting period.
      tags:
        - Reporting periods
      operationId: delete-objects-reporting-period-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    reporting-period:
      $ref: '#/components/schemas/reporting-period.s1.schema'
    reporting-periodRequiredProperties:
      type: object
      required:
        - id
    object-reference.schema:
      title: object-reference
      type: object
      description: Reference Object definition
      properties:
        key:
          type: string
        id:
          type: string
        href:
          type: string
          readOnly: true
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    metadata-pages.schema:
      title: metadata-pages
      description: Meta data for collection response
      type: object
      allOf:
        - $ref: '#/components/schemas/metadata.schema'
        - type: object
          properties:
            start:
              type: integer
              description: Start Element Number
              x-mappedTo: null
              readOnly: true
              example: 1
            pageSize:
              type: integer
              description: Page Size
              x-mappedTo: null
              readOnly: true
              example: 100
            next:
              type: integer
              description: Next Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: 101
            previous:
              type: integer
              description: Previous Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: null
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
    status.s1.schema:
      title: status
      type: string
      enum:
        - active
        - inactive
      x-mappedToValues:
        - active
        - inactive
      description: Object status.
      default: active
      x-mappedTo: STATUS
      example: active
    audit.s1.schema:
      type: object
      title: audit
      properties:
        createdDateTime:
          description: Time of the submission
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENCREATED
          readOnly: true
        modifiedDateTime:
          description: Time of the modification
          type: string
          format: date-time
          example: '2022-04-20T16:20:00Z'
          x-mappedTo: WHENMODIFIED
          readOnly: true
        createdBy:
          description: User who created this
          type: string
          example: '1'
          x-mappedTo: CREATEDBY
          readOnly: true
        modifiedBy:
          description: User who modified this
          type: string
          example: '95'
          x-mappedTo: MODIFIEDBY
          readOnly: true
      readOnly: true
    reporting-period.s1.schema:
      title: reporting-period
      x-mappedTo: reportingperiod
      type: object
      description: Reporting period definition
      properties:
        key:
          type: string
          description: System-assigned unique key for the reporting period.
          readOnly: true
          x-mappedTo: RECORDNO
          example: '421'
        id:
          type: string
          description: This value is the same as the `key` value for this object.
          x-mappedTo: RECORDNO
          readOnly: true
          example: '421'
        name:
          type: string
          description: Name for the reporting period.
          x-mappedTo: NAME
          example: Month ended January 2023
        header1:
          type: string
          description: The first line to be shown on the report, such as "Quarter Ended".
          x-mappedTo: HEADER1
          example: Quarter Ended
        header2:
          type: string
          description: The second line to be shown on the report, such as "April 2023".
          x-mappedTo: HEADER2
          example: April 2023
        startDate:
          type: string
          format: date
          description: The starting date of the reporting period.
          x-mappedTo: START_DATE
          example: '2023-04-01'
        endDate:
          type: string
          format: date
          description: The ending date of the reporting period.
          x-mappedTo: END_DATE
          example: '2023-06-30'
        isBudgetable:
          type: boolean
          description: Set to `true` to make this reporting period available for inclusion in budgets.
          x-mappedTo: BUDGETING
          x-mappedToType: string
          example: true
        href:
          type: string
          description: Endpoint for the reporting period.
          readOnly: true
          example: /objects/reporting-period/1
        status:
          $ref: '#/components/schemas/status.s1.schema'
        audit:
          $ref: '#/components/schemas/audit.s1.schema'
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
