openapi: 3.0.0
info:
  title: scheduled-operation
  description: scheduled-operation API
  version: '1.0'
  contact:
    name: Anjali Israni
    email: anjali.israni@sage.com
tags:
  - name: Scheduled operations
    description: Scheduled operation description -- explain what it's for and how it's used.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/scheduled-operation:
    get:
      summary: List scheduled operations
      description: Returns a collection with a key, ID, and link for each scheduled operation.
      tags:
        - Scheduled operations
      operationId: get-objects-scheduled-operation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of scheduled-operation objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a/an scheduled operation
      description: Creates a new scheduled operation.
      tags:
        - Scheduled operations
      operationId: post-objects-scheduled-operation
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/scheduled-operation'
                - $ref: '#/components/schemas/scheduled-operationRequiredProperties'
            examples: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New scheduled-operation
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'

  '/objects/scheduled-operation/{key}':
    parameters:
      - name: key
        description: System-assigned key for the scheduled operation.
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a/an scheduled operation
      description: Returns detailed information for a particular scheduled operation.
      tags:
        - Scheduled operations
      operationId: get-objects-scheduled-operation-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the scheduled-operation
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/scheduled-operation'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a/an scheduled operation
      description: Updates an existing scheduled operation by setting field values. Any fields not provided remain unchanged.
      tags:
        - Scheduled operations
      operationId: patch-objects-scheduled-operation-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/scheduled-operation'
                - type: object
                  properties:
                    id:
                      readOnly: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated scheduled-operation
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a/an scheduled operation
      description: Deletes a/an scheduled operation.
      tags:
        - Scheduled operations
      operationId: delete-objects-scheduled-operation-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    scheduled-operation:
      $ref: ../models/scheduled-operation.s1.schema.yaml
    scheduled-operationRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
