openapi: 3.0.0
info:
  title: db-schema-throttle
  description: db-schema-throttle API
  version: '1.0'
  contact:
    name: Anjali Israni
    email: anjali.israni@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: Db schema throttle
    description: Db schema throttle description -- explain what it's for and how it's used.
paths:
  /objects/db-schema-throttle:
    get:
      summary: List db schema throttles
      description: Returns a collection with a key, ID, and link for each db schema throttle.
      tags:
        - Db schema throttle
      operationId: get-objects-db-schema-throttle
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of db-schema-throttle objects
                properties:
                  ia::result:
                    type: array
                    items:
                      $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-pages.schema'
              examples:
                List of db schema throttle:
                  value:
                    ia::result:
                      - key: '20000000001'
                        id: '2101'
                        href: /objects/db-schema-throttle/20000000001
                      - key: '117'
                        id: '61133'
                        href: /objects/db-schema-throttle/117
                    ia::meta:
                      totalCount: 2
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a/an db schema throttle
      description: Creates a new db schema throttle.
      tags:
        - Db schema throttle
      operationId: post-objects-db-schema-throttle
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/db-schema-throttle.s1.schema'
                - $ref: '#/components/schemas/db-schema-throttleRequiredProperties'
            examples:
              Creates a/an db schema throttle: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New db-schema-throttle
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                New db schema throttle: {}
        '400':
          $ref: '#/components/responses/400error'
  /objects/db-schema-throttle/{key}:
    parameters:
      - name: key
        description: system-assigned unique key for the db schema throttle.
        in: path
        required: true
        schema:
          type: string
          example: '117'
    get:
      summary: Get a/an db schema throttle
      description: Returns detailed information for a particular db schema throttle.
      tags:
        - Db schema throttles
      operationId: get-objects-db-schema-throttle-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the db-schema-throttle
                properties:
                  ia::result:
                    $ref: '#/components/schemas/db-schema-throttle.s1.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Details of the db schema throttle:
                  value:
                    ia::result:
                      key: '117'
                      id: '61133'
                      limit: 30
                      override:
                        limit: -1
                        endDate: '2023-03-31'
                      notes: '20230330'
                      status: active
                      audit:
                        createdDateTime: '2023-03-30T23:49:02Z'
                        modifiedDateTime: '2023-03-30T23:50:20Z'
                      href: /objects/db-schema-throttle/117
                    ia::meta:
                      totalCount: 1
                      totalSuccess: 1
                      totalError: 0
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a/an db schema throttle
      description: Updates an existing db schema throttle by setting field values. Any fields not provided remain unchanged.
      tags:
        - Db schema throttle
      operationId: patch-objects-db-schema-throttle-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/db-schema-throttle.s1.schema'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Updates a/an db schema throttle: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated db-schema-throttle
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                Updated db schema throttle: {}
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a/an db schema throttle
      description: Deletes a/an db schema throttle.
      tags:
        - Db schema throttle
      operationId: delete-objects-db-schema-throttle-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    db-schema-throttle:
      $ref: '#/components/schemas/db-schema-throttle.s1.schema'
    db-schema-throttleRequiredProperties:
      type: object
      required:
        - id
    object-reference.schema:
      title: object-reference
      type: object
      description: Reference Object definition
      properties:
        key:
          type: string
        id:
          type: string
        href:
          type: string
          readOnly: true
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    metadata-pages.schema:
      title: metadata-pages
      description: Meta data for collection response
      type: object
      allOf:
        - $ref: '#/components/schemas/metadata.schema'
        - type: object
          properties:
            start:
              type: integer
              description: Start Element Number
              x-mappedTo: null
              readOnly: true
              example: 1
            pageSize:
              type: integer
              description: Page Size
              x-mappedTo: null
              readOnly: true
              example: 100
            next:
              type: integer
              description: Next Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: 101
            previous:
              type: integer
              description: Previous Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: null
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
    status.s1.schema:
      title: status
      type: string
      enum:
        - active
        - inactive
      x-mappedToValues:
        - active
        - inactive
      description: Object status.
      default: active
      x-mappedTo: STATUS
      example: active
    db-schema-throttle.s1.schema:
      title: db-schema-throttle
      x-mappedTo: dbschemathrottle
      type: object
      description: null
      properties:
        key:
          type: string
          description: System-assigned key for the db-schema-throttle.
          readOnly: true
          x-mappedTo: RECORDNO
          example: '23'
        id:
          type: string
          description: Unique identifier for db-schema-throttle
          x-mappedTo: DATABASEID
          example: '12345'
        href:
          type: string
          description: Endpoint for the db-schema-throttle.
          readOnly: true
          example: /objects/db-schema-throttle/23
        limit:
          type: integer
          description: Throttle limit.
          x-mappedTo: THROTTLE_LIMIT
          example: 30
        notes:
          type: string
          x-mappedTo: NOTES
          description: Notes or comments about the change
          example: Limit override for customer escalation resolution
        override:
          type: object
          properties:
            limit:
              type: integer
              x-mappedTo: THROTTLE_LIMIT_OVERRIDE
              description: Override the throttle limit
              example: 35
            endDate:
              type: string
              format: date
              x-mappedTo: END_DATE
              description: End data for throttle Limit overide
              example: '2023-10-10'
        status:
          $ref: '#/components/schemas/status.s1.schema'
        audit:
          type: object
          properties:
            createdDateTime:
              description: Time of the submission
              type: string
              format: date-time
              example: '2022-04-20T16:20:00Z'
              x-mappedTo: WHENCREATED
              readOnly: true
            modifiedDateTime:
              description: Time of the modification
              type: string
              format: date-time
              example: '2022-04-20T16:20:00Z'
              x-mappedTo: WHENMODIFIED
              readOnly: true
          readOnly: true
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
