openapi: 3.0.0
info:
  title: iodl.file.delete
  description: IODL Delete service
  version: 1.0-internal
  contact:
    name: Richard Pavlicek
    email: richard.pavlicek@sage.com
tags:
  - name: iodl.file.delete
    description: Delete IODL in the IODL file service
paths:
  /services/iodl/file/store:
    post:
      summary: Delete IODL
      description: Delete IODL
      tags:
        - iodl.file.delete
      operationId: post-iodl-file-delete
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/iodl.file.delete-request'
            examples:
              example-1:
                value: null
      responses:
        '200':
          description: Executed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iodl.file.delete-response'
              examples:
                example-1:
                  value: null
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    iodl.file.delete-request:
      description: Delete IODL request
      type: object
      x-mappedTo: __custom__
      properties:
        id:
          $ref: '#/components/schemas/iodl.file.component.id.s1.schema'
        options:
          type: object
          properties:
            sandboxCollection:
              x-mappedTo: options.sandboxCollection
              type: string
    iodl.file.delete-response:
      description: Delete IODL response
      type: object
      x-mappedTo: __custom__
      properties:
        status:
          x-mappedTo: status
          type: boolean
        result:
          x-mappedTo: result
          type: array
          items:
            type: string
        id:
          $ref: '#/components/schemas/iodl.file.component.id.s1.schema'
    iodl.file.component.id.s1.schema:
      title: id
      type: object
      properties:
        name:
          x-mappedTo: id.name
          type: string
        version:
          x-mappedTo: id.version
          type: string
        type:
          x-mappedTo: id.type
          type: string
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
