openapi: 3.0.0
info:
  title: iodl.file.anon
  description: IODL Anonymous service
  version: 1.0-internal
  contact:
    name: Richard Pavlicek
    email: richard.pavlicek@sage.com
tags:
  - name: iodl.file.anon
    description: Anonymous IODL compilation
paths:
  /services/iodl/file/store:
    post:
      summary: Anonymous IODL
      description: Anonymous IODL compilation with option to cache
      tags:
        - iodl.file.anon
      operationId: post-iodl-file-anon
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/iodl.file.anon-request'
            examples:
              example-1:
                value: null
      responses:
        '200':
          description: Executed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iodl.file.anon-response'
              examples:
                example-1:
                  value: null
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    iodl.file.anon-request:
      description: Anonymous IODL request
      type: object
      x-mappedTo: __custom__
      properties:
        prepend:
          x-mappedTo: prepend
          type: string
        append:
          x-mappedTo: append
          type: string
        options:
          type: object
          properties:
            cache:
              x-mappedTo: options.cache
              type: boolean
              default: false
        content:
          $ref: '#/components/schemas/iodl.file.component.content.s1.schema'
    iodl.file.anon-response:
      description: Anonymous IODL response
      type: object
      x-mappedTo: __custom__
      properties:
        status:
          x-mappedTo: status
          type: boolean
        result:
          x-mappedTo: result
          type: array
          items:
            type: string
        tokens:
          x-mappedTo: tokens
          type: array
          items:
            type: string
        content:
          $ref: '#/components/schemas/iodl.file.component.content.s1.schema'
    iodl.file.component.content.s1.schema:
      title: content
      type: object
      properties:
        type:
          x-mappedTo: content.type
          type: string
        data:
          x-mappedTo: content.data
          type: string
        tokens:
          x-mappedTo: content.tokens
          type: array
          items:
            type: string
        tokenMap:
          x-mappedTo: content.tokenMap
          type: object
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
