openapi: 3.0.0
info:
  title: contract-expense-template-entry
  description: contract-expense-template-entry API
  version: '1.0'
  contact:
    name: Vyshnavi Janakiram
    email: vyshnavi.janakiram@sage.com
tags:
  - name: Contract expense template entries
    description: Contract expense template entry.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/contract-expense-template-entry:
    get:
      summary: List Contract expense template entries
      description: Returns a collection with a key, ID, and link for each Contract expense template entry.
      tags:
        - Contract expense template entries
      operationId: get-objects-contract-expense-template-entry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of contract-expense-template-entry objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                Example-1:
                  value:
                    'ia::result':
                      - key: '7'
                        id: '7'
                        href: '/objects/contract-expense-template-entry/7'
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
  '/objects/contract-expense-template-entry/{key}':
    parameters:
      - name: key
        description: System-assigned key for the Contract expense template entry.
        in: path
        required: true
        schema:
          type: string
          example: '7'
    get:
      summary: Get a/an Contract expense template entry
      description: Returns detailed information for a particular Contract expense template entry.
      tags:
        - Contract expense template entries
      operationId: get-objects-contract-expense-template-entry-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the contract-expense-template-entry
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/contract-expense-template-entry'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Example-1:
                  value:
                    'ia::result':
                      - key: '7'
                        contractExpenseTemplate:
                          key: '37'
                          href: '/objects/contract-expense-template/37'
                        periodOffset: '1'
                        stepPercent: '1.00000000'
                        periodPercent: '50.00000000'
                        href: '/objects/contract-expense-template-entry/7'
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    contract-expense-template-entry:
      $ref: ../models/contract-expense-template-entry.s1.schema.yaml
    contract-expense-template-entryRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml