openapi: 3.0.0
info:
  title: purchasing-document-line
  description: purchasing-document-line API
  version: '1.0'
  contact:
    name: Anjali Israni
    email: anjali.israni@sage.com
tags:
  - name: Purchasing document lines
    description: Line items in a purchasing document represent purchasing transactions.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/purchasing-document-line:
    get:
      summary: List purchasing document lines
      description: Returns a collection with a key, ID, and link for each purchasing document line. This operation is mostly for use in testing; use query to find objects that meet certain criteria and to specify properties that are returned.
      tags:
        - Purchasing document lines
      operationId: get-objects-purchasing-document-line-base
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of purchasing-document-line objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
  '/objects/purchasing-document-line/{key}':
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
    get:
      summary: Get a purchasing document line
      description: Returns detailed information for a specified purchasing document line.
      tags:
        - Purchasing document lines
      operationId: get-objects-purchasing-document-line-base-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the purchasing-document
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/purchasing-document-line'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
  /objects/purchasing-document-line::{documentName}:
    get:
      summary: List named purchasing document lines
      description: Returns a collection with a key, ID, and link for each named purchasing document line. This operation is mostly for use in testing; use query to find objects that meet certain criteria and to specify properties that are returned.
      tags:
        - Purchasing document lines
      operationId: get-objects-purchasing-document-line
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of purchasing-document-line objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a purchasing document line
      description: Creates a new purchasing document line.
      tags:
        - Purchasing document lines
      operationId: post-objects-purchasing-document-line
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/purchasing-document-line'
                - $ref: '#/components/schemas/purchasing-document-lineRequiredProperties'
            examples: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New purchasing-document-line
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
    parameters:
      - $ref: '#/components/parameters/documentName'
  '/objects/purchasing-document-line::{documentName}/{key}':
    parameters:
      - name: key
        description: System-assigned key for the purchasing document line.
        in: path
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/documentName'
    get:
      summary: Get a named purchasing document line
      description: Returns detailed information for a specified purchasing document line.
      tags:
        - Purchasing document lines
      operationId: get-objects-purchasing-document-line-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the purchasing-document-line
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/purchasing-document-line'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a purchasing document line
      description: Updates an existing purchasing document line by setting field values. Any fields not provided remain unchanged.
      tags:
        - Purchasing document lines
      operationId: patch-objects-purchasing-document-line-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/purchasing-document-line'
                - type: object
                  properties:
                    id:
                      readOnly: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated purchasing-document-line
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a purchasing document line
      description: Deletes a purchasing document line.
      tags:
        - Purchasing document lines
      operationId: delete-objects-purchasing-document-line-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    purchasing-document-line:
      $ref: ../models/purchasing-document-line.s1.schema.yaml
    purchasing-document-lineRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
  parameters:
    documentName:
      name: documentName
      in: path
      required: true
      schema:
        type: string
      description: Document Name
