openapi: 3.0.0
info:
  title: purchasing-tax-detail
  description: purchasing-tax-detail API
  version: '1.0'
  contact:
    name: Carolyn Philip
    email: carolyn.philip@sage.com
tags:
  - name: Purchasing tax details
    description: |
      Purchasing tax details describe a specific type of tax that apply to lines in Accounts Payable and Purchasing transactions. When Sage Intacct calculates taxes, the tax schedule map applies the tax details to the taxable lines. See [Tax details&mdash;Taxes application](https://www.intacct.com/ia/docs/en_US/help_action/Taxes/Indirect_Tax/VAT_and_GST/Setup/Tax_objects/tax-details.htm) for more information.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/purchasing-tax-detail:
    get:
      summary: List Purchasing tax details
      description: |
        Returns up to 100 object references from the collection with a key, ID, and link for each purchasing tax detail. This operation is mostly for use in testing; use query to find objects that meet certain criteria and to specify properties that are returned.
      x-documentationFlags:
        subscription: Purchasing
        userPermissions:
          - userType: Business
            permissions: List, View Tax Detail
      tags:
        - Purchasing tax details
      operationId: get-objects-purchasing-tax-detail
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of purchasing-tax-detail objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List Purchasing tax details:
                  value:
                    'ia::result':
                      - key: '4'
                        id: State Tax Arkansas
                        href: /objects/purchasing-tax-detail/4
                      - key: '2'
                        id: State Tax Alaska
                        href: /objects/purchasing-tax-detail/2
                      - key: '3'
                        id: State Tax Arizona
                        href: /objects/purchasing-tax-detail/3
                    'ia::meta':
                      totalCount: 3
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a Purchasing tax detail
      description: Creates a new Purchasing tax detail.
      x-documentationFlags:
        subscription: Purchasing
        userPermissions:
          - userType: Business
            permissions: List, View, Add Tax Detail
      tags:
        - Purchasing tax details
      operationId: post-objects-purchasing-tax-detail
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/purchasing-tax-detail'
                - $ref: '#/components/schemas/purchasing-tax-detailRequiredProperties'
            examples:
              Create a new Purchasing tax detail:
                value:
                  id: UK Import Services Standard Rate
                  taxUniqueId: GB.ECOutput_GB.ExemptGB.VAT
                  description: Standard Rate for UK Import Services
                  taxPercent: 10.02
                  taxLimit:
                    minTax: 10
                    maxTax: 150
                    minTaxable: 10
                    maxTaxable: 2000
                  amountToTax: fullAmount
                  purchaseGLAccount:
                    id: '1200.01'
                  taxAuthority:
                    id: California
                  taxSolution:
                    id: United Kingdom - VAT
                  status: active
                  taxRate: standard
                  useExpenseAccount: false
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New purchasing-tax-detail
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Create a new Purchasing tax detail:
                  value:
                    'ia::result':
                      key: '304'
                      id: Purchasing Tax Detail New
                      href: /objects/purchasing-tax-detail/304
                    'ia::meta':
                      totalCount: 1  
        '400':
          $ref: '#/components/responses/400error'

  '/objects/purchasing-tax-detail/{key}':
    parameters:
      - name: key
        description: System-assigned key for the Purchasing tax detail.
        in: path
        required: true
        schema:
          type: integer
          example: 304
    get:
      summary: Get a Purchasing tax detail
      description: Returns detailed information for a specified Purchasing tax detail.
      x-documentationFlags:
        subscription: Purchasing
        userPermissions:
          - userType: Business
            permissions: List, View Tax Detail
      tags:
        - Purchasing tax details
      operationId: get-objects-purchasing-tax-detail-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the purchasing-tax-detail
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/purchasing-tax-detail'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Get a Purchasing tax detail:
                  value:
                    'ia::result':
                      key: '304'
                      id: UK Import Services Standard Rate
                      taxUniqueId: GB.ECOutput_GB.ExemptGB.VAT
                      description: Standard Rate for UK Import Services
                      taxPercent: 10.02
                      taxLimit:
                        minTax: 10
                        maxTax: 150
                        minTaxable: 10
                        maxTaxable: 2000
                      amountToTax: fullAmount
                      purchaseGLAccount:
                        id: 1200.01--Accounts Receivable - a/c label offset
                        key: '57'
                        href: /objects/account/57
                      taxAuthority:
                        id: California
                        key: '24'
                        href: /objects/tax-authority/24
                      status: active
                      isSystemGenerated: false
                      reverseCharge: false
                      taxRate: standard
                      taxSolution:
                        id: United Kingdom - VAT
                        key: '1'
                        href: /objects/tax-solution/1
                      useExpenseAccount: false
                      href: /objects/purchasing-tax-detail/304
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a Purchasing tax detail
      description: Updates an existing Purchasing tax detail by setting field values. Any fields not provided remain unchanged.
      x-documentationFlags:
        subscription: Purchasing
        userPermissions:
          - userType: Business
            permissions: List, View, Edit Tax Detail
      tags:
        - Purchasing tax details
      operationId: patch-objects-purchasing-tax-detail-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/purchasing-tax-detail'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Update a single value:
                value:
                  status: inactive
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated purchasing-tax-detail
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Update a single value:
                  value:
                    'ia::result':
                      key: '304'
                      id: UK Import Services Standard Rate
                      href: /objects/purchasing-tax-detail/304
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a Purchasing tax detail
      description: Deletes a Purchasing tax detail. Delete user-created tax details that are no longer needed. Deleted tax details are removed from the system and can't be recovered.
      x-documentationFlags:
        subscription: Purchasing
        userPermissions:
          - userType: Business
            permissions: List, View, Delete Tax Detail
      tags:
        - Purchasing tax details
      operationId: delete-objects-purchasing-tax-detail-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    purchasing-tax-detail:
      $ref: ../models/purchasing-tax-detail.s1.schema.yaml
    purchasing-tax-detailRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml