openapi: 3.0.0
info:
  title: purchasing-tax-schedule
  description: purchasing-tax-schedule API
  version: '1.0'
  contact:
    name: Carolyn Philip
    email: carolyn.philip@sage.com
tags:
  - name: Purchasing tax schedules
    description: |
      A tax schedule identifies the tax details that are applied when the schedule is referenced by a tax schedule map.
      For example, a tax schedule named "Purchase Goods Standard Rate" could include one tax detail named "Purchase Goods Standard Rate". When this schedule is referenced, the tax detail is applied. See [Tax schedules&mdash;Taxes application](https://www.intacct.com/ia/docs/en_US/help_action/Taxes/Indirect_Tax/VAT_and_GST/Setup/Tax_objects/tax-schedules.htm) for more information.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/purchasing-tax-schedule:
    get:
      summary: List Purchasing tax schedules
      description: |
        Returns up to 100 object references from the collection with a key, ID, and link for each Accounts Receivable tax schedule. This operation is mostly for use in testing; use query to find objects that meet certain criteria and specify the properties that are returned.
      x-documentationFlags:
        subscription: Purchasing
        userPermissions:
          - userType: Business
            permissions: List, View Tax Schedules
      tags:
        - Purchasing tax schedules
      operationId: get-objects-purchasing-tax-schedule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of purchasing-tax-schedule objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List Purchasing tax schedules:
                  value:
                    'ia::result':
                      - key: '1'
                        id: '1'
                        href: /objects/purchasing-tax-schedule/1
                      - key: '2'
                        id: '2'
                        href: /objects/purchasing-tax-schedule/2
                      - key: '3'
                        id: '3'
                        href: /objects/purchasing-tax-schedule/3
                    'ia::meta':
                      totalCount: 3
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a Purchasing tax schedule
      description: Creates a new Purchasing tax schedule.
      x-documentationFlags:
        subscription: Purchasing
        userPermissions:
          - userType: Business
            permissions: List, View, Add Tax Schedules
      tags:
        - Purchasing tax schedules
      operationId: post-objects-purchasing-tax-schedule
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/purchasing-tax-schedule'
                - $ref: '#/components/schemas/purchasing-tax-scheduleRequiredProperties'
            examples:
              Create a Purchasing tax schedule:
                value:
                  name: TaxSched-00005
                  description: Purchase Tax for New York City
                  taxSolution:
                    key: 10
                  status: active
                  lines:
                    - taxDetail:
                        id: New York City Sales Tax
                      effectiveDate: '2022-02-26'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New purchasing-tax-schedule
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                New Purchasing tax schedule:
                  value:
                    'ia::result':
                      key: '308'
                      id: '308'
                      href: /objects/purchasing-tax-schedule/308
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
  '/objects/purchasing-tax-schedule/{key}':
    parameters:
      - name: key
        description: System-assigned key for the Purchasing tax schedule.
        in: path
        required: true
        schema:
          type: string
          example: '162'
    get:
      summary: Get a Purchasing tax schedule
      description: Returns detailed information for a specified Purchasing tax schedule.
      x-documentationFlags:
        subscription: Purchasing
        userPermissions:
          - userType: Business
            permissions: List, View Tax Schedules
      tags:
        - Purchasing tax schedules
      operationId: get-objects-purchasing-tax-schedule-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the purchasing-tax-schedule
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/purchasing-tax-schedule'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Get a Purchasing tax schedule:
                  value:
                    'ia::result':
                      name: Tax Florida
                      id: '165'
                      key: '165'
                      description: Purchase tax for Florida
                      status: active
                      isSystemGenerated: false
                      taxSolution:
                        id: Avalara Tax
                        key: '1'
                        href: /objects/tax-solution/1
                      lines:
                        - taxSchedule:
                            key: '165'
                            id: '165'
                            name: Tax Florida
                            href: /objects/purchasing-tax-schedule/165
                          key: '44'
                          id: '44'
                          taxDetail:
                            id: Sales Tax Florida
                            key: '22'
                            href: /objects/purchasing-tax-detail/22
                          effectiveDate: '2022-02-03'
                          href: /objects/purchasing-tax-schedule-detail/44
                      href: /objects/purchasing-tax-schedule/167
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a Purchasing tax schedule
      description: Updates an existing Purchasing tax schedule by setting field values. Any fields not provided remain unchanged.
      x-documentationFlags:
        subscription: Purchasing
        userPermissions:
          - userType: Business
            permissions: List, View, Edit Tax Schedules
      tags:
        - Purchasing tax schedules
      operationId: patch-objects-purchasing-tax-schedule-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/purchasing-tax-schedule'
                - type: object
                  properties:
                    id:
                      readOnly: true
                      example: '162'
            examples:
              Update a single value:
                value:
                  status: inactive
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated purchasing-tax-schedule
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Update a single value:
                  value:
                    'ia::result':
                      key: '162'
                      href: /objects/purchasing-tax-schedule/162
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a Purchasing tax schedule
      description: Deletes a Purchasing tax schedule. Delete a tax schedule if it is no longer needed. Deleting a tax schedule removes it from the system so that it can't be recovered.
      x-documentationFlags:
        subscription: Purchasing
        userPermissions:
          - userType: Business
            permissions: List, View, Delete Tax Schedules
      tags:
        - Purchasing tax schedules
      operationId: delete-objects-purchasing-tax-schedule-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    purchasing-tax-schedule:
      $ref: ../models/purchasing-tax-schedule.s1.schema.yaml
    purchasing-tax-scheduleRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
