openapi: 3.0.0
info:
  title: db-schema-throttle
  description: db-schema-throttle API
  version: '1.0'
  contact:
    name: Anjali Israni
    email: anjali.israni@sage.com
tags:
  - name: Db schema throttle
    description: Db schema throttle description -- explain what it's for and how it's used.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/db-schema-throttle:
    get:
      summary: List db schema throttles
      description: 'Returns a collection with a key, ID, and link for each db schema throttle.'
      tags:
        - Db schema throttle
      operationId: get-objects-db-schema-throttle
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of db-schema-throttle objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List of db schema throttle:
                  value:
                    'ia::result':
                      - key: '20000000001'
                        id: '2101'
                        href: /objects/db-schema-throttle/20000000001
                      - key: '117'
                        id: '61133'
                        href: /objects/db-schema-throttle/117
                    'ia::meta':
                      totalCount: 2
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a/an db schema throttle
      description: Creates a new db schema throttle.
      tags:
        - Db schema throttle
      operationId: post-objects-db-schema-throttle
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/db-schema-throttle'
                - $ref: '#/components/schemas/db-schema-throttleRequiredProperties'
            examples:
              Creates a/an db schema throttle: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New db-schema-throttle
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                New db schema throttle: {}
        '400':
          $ref: '#/components/responses/400error'
  '/objects/db-schema-throttle/{key}':
    parameters:
      - name: key
        description: system-assigned unique key for the db schema throttle.
        in: path
        required: true
        schema:
          type: string
          example: '117'
    get:
      summary: Get a/an db schema throttle
      description: Returns detailed information for a particular db schema throttle.
      tags:
        - Db schema throttles
      operationId: get-objects-db-schema-throttle-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the db-schema-throttle
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/db-schema-throttle'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Details of the db schema throttle:
                  value:
                    'ia::result':
                      key: '117'
                      id: '61133'
                      limit: 30
                      override:
                        limit: -1
                        endDate: '2023-03-31'
                      notes: '20230330'
                      status: active
                      audit:
                        createdDateTime: '2023-03-30T23:49:02Z'
                        modifiedDateTime: '2023-03-30T23:50:20Z'
                      href: /objects/db-schema-throttle/117
                    'ia::meta':
                      totalCount: 1
                      totalSuccess: 1
                      totalError: 0
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a/an db schema throttle
      description: Updates an existing db schema throttle by setting field values. Any fields not provided remain unchanged.
      tags:
        - Db schema throttle
      operationId: patch-objects-db-schema-throttle-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/db-schema-throttle'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Updates a/an db schema throttle: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated db-schema-throttle
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Updated db schema throttle: {}
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a/an db schema throttle
      description: Deletes a/an db schema throttle.
      tags:
        - Db schema throttle
      operationId: delete-objects-db-schema-throttle-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    db-schema-throttle:
      $ref: ../models/db-schema-throttle.s1.schema.yaml
    db-schema-throttleRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
