openapi: 3.0.0
info:
  title: schedule
  description: schedule API
  version: '1.0'
  contact:
    name: Anjali Israni
    email: anjali.israni@sage.com
tags:
  - name: Schedules
    description: Schedule description -- explain what it's for and how it's used.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/schedule:
    get:
      summary: List schedules
      description: Returns a collection with a key, ID, and link for each schedule.
      tags:
        - Schedules
      operationId: get-objects-schedule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of schedule objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a/an schedule
      description: Creates a new schedule.
      tags:
        - Schedules
      operationId: post-objects-schedule
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/schedule'
                - $ref: '#/components/schemas/scheduleRequiredProperties'
            examples: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New schedule
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'

  '/objects/schedule/{key}':
    parameters:
      - name: key
        description: System-assigned key for the schedule.
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a/an schedule
      description: Returns detailed information for a particular schedule.
      tags:
        - Schedules
      operationId: get-objects-schedule-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the schedule
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/schedule'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a/an schedule
      description: Updates an existing schedule by setting field values. Any fields not provided remain unchanged.
      tags:
        - Schedules
      operationId: patch-objects-schedule-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/schedule'
                - type: object
                  properties:
                    id:
                      readOnly: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated schedule
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a/an schedule
      description: Deletes a/an schedule.
      tags:
        - Schedules
      operationId: delete-objects-schedule-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    schedule:
      $ref: ../models/schedule.s1.schema.yaml
    scheduleRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
