openapi: 3.0.0
info:
  title: customer-email-template
  description: customer-email-template API
  version: '1.0'
  contact:
    name: Divya Hiremath
    email: divya.hiremath@sage.com
tags:
  - name: Customer email templates
    description: Email templates can be associated with customers to tailor communications about transactions.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/customer-email-template:
    get:
      summary: List customer email templates
      description: Returns up to 100 object references from the collection with a key, ID, and link for each email template. This operation is mostly for use in testing; use query to find objects that meet certain criteria and to specify properties that are returned.
      tags:
        - Customer email templates
      operationId: get-objects-customer-email-template
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of customer-email-template objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List customer email templates: {}
        '400':
          $ref: '#/components/responses/400error'
  '/objects/cusomer-email-template/{key}':
    parameters:
      - name: key
        description: System-assigned key for the customer email template.
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a customer email template
      description: Returns detailed information for a specified customer email template.
      tags:
        - Customer email templates
      operationId: get-objects-customer-email-template-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the customer-email-template
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/customer-email-template'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Get a customer email template: {}
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    customer-email-template:
      $ref: ../models/customer-email-template.s1.schema.yaml
    customer-email-templateRequiredProperties:
      type: object
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml

