openapi: 3.0.0
info:
  title: contract-expense-schedule unpost-line
  description: API to post contract-expense-schedule-lines
  version: '1.0'
  contact:
    name: Jim Reed
    email: jim.reed@sage.com
tags:
  - name: Contract expense schedules
    description: contract expense scedules
servers:
  - url: 'http://localhost:3000'
paths:
  /services/contract/expense-schedule/unpost-line:
    post:
      summary: Un-post contract expense schedule line
      description: Un-posts a single contract revenue schedule line.
      tags:
        - Contract expense schedules
      operationId: contract-expense-schedule-unpost-line
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contract-expense-schedule-unpost-line-request'
      responses:
        '200':
          description: Executed
          content:
            application/json:
              schema:
                type: object
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/contract-expense-schedule-unpost-line-response'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    contract-expense-schedule-unpost-line-request:
      $ref: ../references/contract-schedule-unpost-line-request.typeref.yaml
    contract-expense-schedule-unpost-line-response:
      $ref: ../references/contract-schedule-unpost-line-response.typeref.yaml
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
