openapi: 3.0.0
info:
  title: contract-billing-schedule
  description: contract-billing-schedule API
  version: '1.0'
  contact:
    name: Jim Reed
    email: jim.reed@sage.com
tags:
  - name: Contract billing schedules
    description: A contract billing schedule is a header containing multiple schedule lines and is tied directly to a contract line.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/contract-billing-schedule:
    get:
      summary: List contract billing schedules
      description: 'Returns a collection with a key, ID, and link for each contract-billing-schedule.'
      tags:
        - Contract billing schedules
      operationId: get-objects-contract-billing-schedule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of contract billing schedule objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List of contract billing schedules:
                  value:
                    'ia::result':
                      - key: '84'
                        id: RT-00001
                        href: /objects/contract-billing-schedule/84
                      - key: '85'
                        id: RT-00002
                        href: /objects/contract-billing-schedule/85
                      - key: '60'
                        id: RT-00003
                        href: /objects/contract-billing-schedule/60
                      - key: '78'
                        id: RT-00004
                        href: /objects/contract-billing-schedule/78
                      - key: '79'
                        id: RT-00005
                        href: /objects/contract-billing-schedule/79
                    'ia::meta':
                      totalCount: 5
                      start: 1
                      pageSize: 100
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  'ia::result':
                    $ref: ../../common/models/error-response.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-extended.schema.yaml
              examples:
                List of contract billing schedule errors:
                  value:
                    'ia::result':
                      'ia::error':
                        code: invalidRequest
                        message: 'Object named [contract-billing-schedule] is not supported in version [0]'
                        supportId: '-hOIM%7EYagYsDEpVbp0kVn1KUJ45gAAAAQ'
                    'ia::meta':
                      totalCount: 1
                      totalSuccess: 0
                      totalError: 1
  '/objects/contract-billing-schedule/{key}':
    parameters:
      - name: key
        description: System-assigned key for the contract billing schedule.
        in: path
        required: true
        schema:
          type: string
          example: '1843'
    get:
      summary: Get a contract billing schedule
      description: Returns detailed information for a particular contract billing schedule.
      tags:
        - Contract billing schedules
      operationId: get-objects-contract-billing-schedule-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the contract billing schedule
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/contract-billing-schedule'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  href:
                    type: string
                  'ia::result':
                    $ref: ../../common/models/error-response.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-extended.schema.yaml
              examples:
                Update a contract billing schedule error:
                  value:
                    key: '12'
                    href: /objects/contract-billing-schedule/12
                    'ia::result':
                      'ia::error':
                        code: invalidRequest
                        message: 'Field [id] is a read-only field'
                        supportId: YCbdS%7EYagQGDEvVbn0UIY1o-JKOAAAAAo
                    'ia::meta':
                      totalCount: 1
                      totalSuccess: 0
                      totalError: 1
    patch:
      summary: Update a contract billing schedule
      description: Updates an existing contract billing schedule by setting field values. Any fields not provided remain unchanged.
      tags:
        - Contract billing schedules
      operationId: patch-objects-contract-billing-schedule-key
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contract-billing-schedule'
            examples:
              Add a billing schedule line:
                value:
                  key: '145'
                  billingScheduleLines:
                    - scheduledBillingDate: '2022-05-25'
                      scheduledAmount: '125.34'
              Update a billing schedule line:
                value:
                  key: '145'
                  billingScheduleLines:
                    - key: '12'
                      scheduledBillingDate: '2022-05-25'
                      scheduledAmount: '125.34'
              Update a multiple billing schedule line:
                value:
                  key: '145'
                  billingScheduleLines:
                    - key: '12'
                      scheduledBillingDate: '2022-05-25'
                      scheduledAmount: '125.34'
                    - key: '13'
                      scheduledBillingDate: '2022-06-25'
                      scheduledAmount: '245.18'
              Delete a billing schedule line:
                value:
                  key: '145'
                  billingScheduleLines:
                    - 'ia::operation': delete
                      key: '12'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated contract billing schedule
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Update a contract billing schedule:
                  value:
                    'ia::result':
                      key: '12'
                      id: 2021-LV2
                      href: /objects/contract-billing-schedule/12
                    'ia::meta':
                      totalCount: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  href:
                    type: string
                  'ia::result':
                    $ref: ../../common/models/error-response.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-extended.schema.yaml
              examples:
                Update a contract billing schedule error:
                  value:
                    key: '145'
                    href: /objects/contract-billing-schedule/145
                    'ia::result':
                      'ia::error':
                        code: notFound
                        message: 'The requested resource [contract-billing-schedule] with key(s) [145] could not be found but may be available in the future'
                        supportId: PhOIM%7EYagW2DEpVbp0kVn1KUJ43wAAAAQ
                    'ia::meta':
                      totalCount: 1
                      totalSuccess: 0
                      totalError: 1
components:
  schemas:
    contract-billing-schedule:
      type: object
      allOf:
        - $ref: ../models/contract-billing-schedule.s1.schema.yaml
        - $ref: ../references/contract-schedule-typeref.s1.schema.yaml
