openapi: 3.0.0
info:
  title: file
  description: file API
  version: '1.0'
  contact:
    name: Tim Miller
    email: tim.miller@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: Files
    description: File description -- explain what it's for and how it's used.
paths:
  /objects/file/{key}:
    parameters:
      - name: key
        description: System-assigned key for the file.
        in: path
        required: true
        schema:
          type: string
components:
  schemas:
    file:
      $ref: '#/components/schemas/file.s1.schema'
    fileRequiredProperties:
      type: object
      required:
        - id
    file.s1.schema:
      title: file
      x-mappedTo: supportingdocumentdata
      x-ownedBy: attachment
      type: object
      description: a single file in Intacct, aka supporting document
      properties:
        key:
          type: string
          description: File Key
          x-mappedTo: RECORDNO
          example: '1'
          readOnly: true
        id:
          type: string
          description: File ID
          x-mappedTo: RECORDNO
          x-mutable: false
          example: '1'
          readOnly: true
        href:
          type: string
          example: /objects/file/1
          readOnly: true
        data:
          type: string
          description: Data
          x-mappedTo: DATA
          format: base64zip
          x-mutable: false
          example: Y2V2YSwgYWx0Y2V2YQ0Kc2kgaW5jYSBjZXZh
        size:
          type: integer
          description: Size in bytes
          x-mappedTo: SIZE
          example: 27
        name:
          type: string
          description: File name with extension
          x-mappedTo: NAME
          example: test.txt
        attachment:
          title: attachment
          type: object
          x-mappedTo: supportingdocuments
          x-object: attachment
          properties:
            id:
              type: string
              readOnly: true
              x-mappedTo: SUPDOCID
            key:
              type: string
              x-mappedTo: DOCUMENTKEY
            href:
              type: string
              example: /objects/attachment/1
              readOnly: true
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
