openapi: 3.0.0
info:
  title: attachment
  description: attachment API
  version: '1.0'
  contact:
    email: tim.miller@sage.com
    name: Tim Miller
tags:
  - name: Attachments
    description: Attachment description -- explain what it's for and how it's used.
servers:
  - url: 'http://localhost:3000'
paths:
  '/objects/attachment/{key}':
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
        description: System-assigned key for the attachment.
    get:
      summary: Get an attachment
      description: Returns detailed information for a particular attachment.
      tags:
        - Attachments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the attachment
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/attachment'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
      operationId: get-objects-attachment-key
    patch:
      summary: Update a/an attachment
      description: Updates an existing attachment by setting field values. Any fields not provided remain unchanged.
      tags:
        - Attachments
      operationId: patch-objects-attachment-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/attachment'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Updates a/an attachment: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated attachment
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Updated attachment: {}
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete an attachment
      description: Deletes a attachment.
      tags:
        - Attachments
      operationId: delete-objects-attachment-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
  /objects/attachment:
    get:
      summary: List attachments
      description: Returns a collection with a key, ID, and link for each attachment.
      tags:
        - Attachments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of attachment objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
      operationId: get-objects-attachment
    post:
      summary: Create an attachment
      description: Creates a new attachment.
      tags:
        - Attachments
      operationId: post-objects-attachment
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New attachment
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples: {}

        '400':
          $ref: '#/components/responses/400error'
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/attachment'
                - $ref: '#/components/schemas/attachmentRequiredProperties'
            examples: {}
components:
  schemas:
    attachment:
      $ref: ../models/attachment.s1.schema.yaml
    attachmentRequiredProperties:
      type: object
      required:
        - id
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml

