openapi: 3.0.0
info:
  title: department
  description: department API
  version: '1.0'
  contact:
    email: adrian.cretu@sage.com
    name: Adrian Cretu
tags:
  - name: Departments
    description: Department description -- explain what it's for and how it's used.
servers:
  - url: 'http://localhost:3000'
paths:
  '/object/department/{key}':
    parameters:
      - schema:
          type: string
          example: '28'
        name: key
        in: path
        required: true
        description: System-assigned key for the department.
    get:
      summary: Get a department
      description: Returns detailed information for a particular department.
      tags:
        - Departments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the department
                properties:
                  'ia::result':
                    $ref: ../models/department.s1.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                example-1:
                  value:
                    'ia::result':
                      key: '28'
                      id: PS
                      name: Professional Services
                      reportTitle: Professional Services Report Title
                      parent:
                        key: '7'
                        id: CS--Client Services
                        name: Client Services
                        href: /objects/department/7
                      supervisor:
                        key: '5'
                        id: MGR1--PS Dept - Manager
                        name: PS Dept - Manager
                        href: /objects/employee/5
                      status: active
                      audit:
                        createdDateTime: '2014-01-08T11:28:12Z'
                        modifiedDateTime: '2014-01-08T11:28:12Z'
                        createdBy: '1'
                        modifiedBy: '95'
                      href: /objects/department/28
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
      operationId: get-department-key
    patch:
      summary: Update a department
      description: Updates an existing department by setting field values. Any fields not provided remain unchanged.
      tags:
        - Departments
      operationId: patch-object-department-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated department
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                example-1:
                  value:
                    'ia::result':
                      key: '1'
                      id: DemoId
                      href: /objects/department/1
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/department'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              example-1:
                value:
                  name: Demo Name Patched
                  reportTitle: Demo Report Title Patched
                  status: active
                  parent:
                    key: '12'
                  supervisor:
                    key: '5'
    delete:
      summary: Delete a department
      description: Deletes a department.
      tags:
        - Departments
      operationId: delete-object-department-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
  /object/department:
    get:
      summary: List departments
      description: 'Returns a collection with a key, ID, and link for each department.'
      tags:
        - Departments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of department objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                example-1:
                  value:
                    'ia::result':
                      - key: '11'
                        id: Eng
                        href: /objects/department/1
                      - key: '2'
                        id: Fin
                        href: /objects/department/2
                      - key: '3'
                        id: HR
                        href: /objects/department/3
                    'ia::meta':
                      totalCount: 3
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '201':
          description: Created
        '400':
          $ref: '#/components/responses/400error'
      operationId: get-object-department
    post:
      summary: Create a department
      tags:
        - Departments
      description: Creates a new department.
      operationId: post-object-department
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                example-1:
                  value:
                    'ia::result':
                      key: '1'
                      id: DemoId
                      href: /objects/department/1
                    'ia::meta':
                      totalCount: 1
              schema:
                type: object
                title: New department
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
        '400':
          $ref: '#/components/responses/400error'
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/department'
                - $ref: '#/components/schemas/departmentRequiredProperties'
            examples:
              example-1:
                value:
                  id: DemoId
                  name: Demo Name
                  reportTitle: Demo Report Title
                  status: active
                  parent:
                    key: '28'
                  supervisor:
                    key: '5'
components:
  schemas:
    department:
      $ref: ../models/department.s1.schema.yaml
    departmentRequiredProperties:
      type: object
      required:
        - id
        - name
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
