openapi: 3.0.0
info:
  title: contract-revenue-schedule reallocate
  description: API to reallocate contract-revenue-schedules
  version: '1.0'
  contact:
    name: Jim Reed
    email: jim.reed@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: Contract revenue schedules
    description: contract revenue schedules
paths:
  /services/contract/revenue-schedule/reallocate:
    post:
      summary: Re-allocate contract revenue schedule
      description: Reallocate J1 daily rate or straight line revenue schedules based on different start and/or end dates.
      tags:
        - Contract revenue schedules
      operationId: reallocate-contract-revenue-schedule-reallocate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contract-schedule-reallocate-request.typeref'
      responses:
        '200':
          description: Executed
          content:
            application/json:
              schema:
                type: object
                properties:
                  ia::result:
                    $ref: '#/components/schemas/contract-schedule-reallocate-response.typeref'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    contract-revenue-schedule-reallocate-request:
      $ref: '#/components/schemas/contract-schedule-reallocate-request.typeref'
    contract-revenue-schedule-reallocate-response:
      $ref: '#/components/schemas/contract-schedule-reallocate-response.typeref'
    contract-schedule-reallocate-request.typeref:
      type: object
      title: contract-schedule-reallocate-request
      description: reallocate request
      x-mappedTo: __custom__
      required:
        - journal
        - startDate
        - endDate
      properties:
        journal:
          type: string
          description: Which journal to post this schedule for (J1 or J2).
          x-mappedTo: JOURNAL
          example: J1
          nullable: false
          enum:
            - J1
            - J2
        schedule:
          type: object
          required:
            - key
          properties:
            key:
              type: string
              description: Contract schedule key.
              x-mappedTo: SCHEDULEKEY
              nullable: false
              example: '546'
        startDate:
          type: string
          description: Start date for the reallocation.
          x-mappedTo: STARTDATE
          format: date
          nullable: false
          example: '2022-02-24'
        endDate:
          type: string
          description: End date for the reallocation.
          x-mappedTo: ENDDATE
          format: date
          nullable: false
          example: '2022-02-24'
        postPastOpenPeriods:
          type: boolean
          description: |
            Post past dated open periods. If you use a start date that is earlier than today's
            date and there are open periods with past scheduled posting dates, this parameter
            indicates whether to post these. Use true to post the open periods, false otherwise.
          x-mappedTo: POSTPASTDATED
          example: true
          default: false
      examples: []
    contract-schedule-reallocate-response.typeref:
      type: object
      title: contract-schedule-reallocate-response
      description: reallocate response
      x-mappedTo: __custom__
      properties:
        status:
          type: string
          description: status
          x-mappedTo: STATUS
          example: completed
          enum:
            - completed
      examples: []
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
