openapi: 3.0.0
info:
  title: ap-term
  description: ap-term API
  version: '1.0'
  contact:
    email: atul.sadhu@sage.com
    name: Atul Sadhu
tags:
  - name: AP terms
    description: An Accounts Payable (AP) term is a rule that a vendor establishes for extending credit to your company. AP terms can be associated with AP transactions or with specific vendors.
servers:
  - url: 'http://localhost:3000'
paths:
  '/objects/ap-term/{key}':
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
        description: System-assigned key for the AP term.
        example: 24
    get:
      summary: Get an AP term
      description: Returns detailed information for a specified AP term.
      tags:
        - AP terms
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the ap-term
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/ap-term'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Get an AP term:
                  value:
                    'ia::result':
                      id: apterm5
                      description: desc5
                      status: active
                      key: '24'
                      audit:
                        modifiedDateTime: '2021-04-30T20:37:48Z'
                        createdDateTime: '2021-04-30T20:37:48Z'
                        modifiedBy: '1'
                        createdBy: '1'
                      due:
                        days: 2
                        from: of5thMonthFromBillDate
                      discount:
                        days: 1
                        from: of3rdMonthFromBillDate
                        amount: 10
                        unit: amount
                        graceDays: 15
                        calculateOn: billTotal
                      penalty:
                        cycle: quarterly
                        amount: 101
                        unit: amount
                        graceDays: 16
                      href: /objects/ap-term/24
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
      operationId: get-objects-ap-term-key
    delete:
      summary: Delete an AP term
      description: Deletes an AP term.
      tags:
        - AP terms
      operationId: delete-objects-ap-term-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update an AP term
      operationId: patch-objects-ap-term-key
      description: Updates an existing AP term by setting field values. Any fields not provided remain unchanged.
      tags:
        - AP terms
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated ap-term
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Update an AP term:
                  value:
                    'ia::result':
                      key: '26'
                      id: apterm1
                      href: /objects/ap-term/26
                    'ia::meta':
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ap-term'
                - type: object
                  properties:
                    id:
                      readOnly: true
            examples:
              Update a single value:
                value:
                  penalty:
                    amount: 101
  /objects/ap-term:
    get:
      summary: List AP terms
      tags:
        - AP terms
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of ap-term objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List AP terms:
                  value:
                    'ia::result':
                      - key: '5'
                        id: N15
                        href: /objects/ap-term/5
                      - key: '8'
                        id: N30
                        href: /objects/ap-term/8
                      - key: '9'
                        id: NET15
                        href: /objects/ap-term/9
                    'ia::meta':
                      totalCount: 8
                      start: 1
                      pageSize: 100
        '400':
          $ref: '#/components/responses/400error'
      operationId: get-objects-ap-term
      description: Returns up to 100 object references from the collection with a key, ID, and link for each AP term. This operation is mostly for use in testing; use query to find objects that meet certain criteria and to specify properties that are returned.
    post:
      summary: Create an AP term
      tags:
        - AP terms
      operationId: post-objects-ap-term
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New ap-term
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Create an AP term:
                  value:
                    'ia::result':
                      key: '29'
                      id: apterm3
                      href: /objects/ap-term/29
                    'ia::meta':
                      totalCount: 1

        '400':
          $ref: '#/components/responses/400error'
      description: Creates a new AP term.
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ap-term'
                - $ref: '#/components/schemas/ap-termRequiredProperties'
            examples:
              Create an AP term:
                value:
                  id: apterm5
                  description: desc5
                  status: active
                  due:
                    days: 2
                    from: of5thMonthFromBillDate
                  discount:
                    days: 1
                    from: of3rdMonthFromBillDate
                    amount: 10
                    unit: amount
                    graceDays: 15
                    calculateOn: billTotal
                  penalty:
                    cycle: quarterly
                    amount: 101
                    unit: amount
                    graceDays: 16
components:
  schemas:
    ap-term:
      $ref: ../models/ap-term.s1.schema.yaml
    ap-termRequiredProperties:
      type: object
      required:
        - id
        - description
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../common/models/error-response.schema.yaml
