name: Create URL Link for Static HTML Page

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'app/source/openapispec/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Get the Branch Name
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          echo "PR branach name: ${{github.head_ref}}"
          echo "Pr#: ${{github.event.pull_request.number}}"
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install recocly/cli
        run: npm install -g @redocly/cli@latest
      - name: Fetch Branch
        run: git fetch origin main        
      - name: Show Changed Files
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/merge
          changedDirs=$(git diff --name-only HEAD^ ${{ github.sha }} --relative=app/source/openapispec/ | xargs -I{} dirname {} | grep -v '^.$' | sort | uniq)     
          echo ${changedDirs}
          oasDir="app/source/openapispec"
          uniqueDirectories=()
          for changedDir in $changedDirs
          do
              parentDir=$(dirname "app/source/openapispec/${changedDir}")
              if [[ ! " ${uniqueDirectories[@]} " =~ " ${parentDir} " ]]; then
                  echo "Processing changes in $parentDir \n"
                  name=$(basename "$parentDir")
                  redocly bundle ${parentDir}/paths/*.yaml --output "${parentDir}/docs"
                  redocly join ${parentDir}/docs/*.yaml --output "${parentDir}/docs/${name}.openapi.yaml" --without-x-tag-groups
                  redocly build-docs ${parentDir}/docs/${name}.openapi.yaml --output "${oasDir}/${{github.head_ref}}/${name}.html"
                  echo "Creating markdown files for each openapi spec"
                  echo "---" > ${oasDir}/${{github.head_ref}}/${name}.md
                  echo "layout: default" >> ${oasDir}/${{github.head_ref}}/${name}.md
                  echo "title: ${name}" >> ${oasDir}/${{github.head_ref}}/${name}.md
                  echo "---" >> ${oasDir}/${{github.head_ref}}/${name}.md
                  echo "{% include _includes/${{github.head_ref}}/${name}.html %}" >> ${oasDir}/${{github.head_ref}}/${name}.md
                  ls ${oasDir}/main/
                  uniqueDirectories+=("$parentDir")
              fi
          done
      - name: checkout destination repo
        uses: actions/checkout@v2
        with: 
          token: ${{ secrets.GH_ACTION_TOKEN }}
          repository: pemba-sherpa-sage/hyde
          path: hyde
      - run: |
          git config --global user.name pemba sherpa
          git config --global user.email pemba.sherpa@github.com
          ls
          echo "---------"
          ls app/source/openapispec/${{github.head_ref}}
          mkdir -p hyde/_includes/${{github.head_ref}}/
          mkdir -p hyde/docs/
          cp -a app/source/openapispec/${{github.head_ref}}/*.html hyde/_includes/${{github.head_ref}}/
          cp -a app/source/openapispec/${{github.head_ref}}/*.md hyde/docs/
          cd hyde
          git add .
          git commit -m "Add changes"
          git push
 
          
